import type { BotLevel, Lesson, Puzzle, RoadmapStage, WatchCard } from './types';

export const researchPillars = [
  {
    name: 'Pattern recognition',
    finding: 'The report found that the elite five built huge stores of positions early. The app turns this into daily bite-sized motif recognition, not just random playing.',
  },
  {
    name: 'Calculation under pressure',
    finding: 'Carlsen, Kasparov, Caruana, Aronian and So all calculated well when the position was uncomfortable. The app trains forcing lines before engine review.',
  },
  {
    name: 'Practical resilience',
    finding: 'Extreme Elo comes from low loss rate plus enough conversion. The app rewards saving worse positions and converting small edges, not only checkmates.',
  },
  {
    name: 'Endgame conversion',
    finding: 'The top five win many positions ordinary players drift to draws. Endgames are placed early in the roadmap instead of being treated as optional advanced material.',
  },
  {
    name: 'Preparation and adaptability',
    finding: 'Different styles reached the top: Carlsen pressure, Kasparov prep, Caruana calculation, Aronian creativity, So solidity. The app lets a learner train multiple styles.',
  },
];

export const botLevels: BotLevel[] = [
  {
    id: 'street-400',
    label: 'Street Beginner',
    elo: 400,
    style: 'Random, misses tactics',
    depth: 1,
    noise: 240,
    blunderChance: 0.48,
    description: 'For learning piece movement, legal moves, and basic checkmates.',
  },
  {
    id: 'learner-800',
    label: 'Learner Bot',
    elo: 800,
    style: 'Greedy and tactical',
    depth: 1,
    noise: 150,
    blunderChance: 0.27,
    description: 'Good for spotting free pieces, forks, pins, and basic mates.',
  },
  {
    id: 'club-1200',
    label: 'Club Bot',
    elo: 1200,
    style: 'Basic development and tactics',
    depth: 2,
    noise: 85,
    blunderChance: 0.14,
    description: 'Punishes hanging pieces and careless king safety.',
  },
  {
    id: 'strong-1600',
    label: 'Strong Club Bot',
    elo: 1600,
    style: 'Cleaner tactics, safer king',
    depth: 2,
    noise: 45,
    blunderChance: 0.07,
    description: 'For training calculation before moving.',
  },
  {
    id: 'expert-2000',
    label: 'Expert Bot',
    elo: 2000,
    style: 'Positional plus tactical',
    depth: 2,
    noise: 22,
    blunderChance: 0.025,
    description: 'For practising a calm, low-blunder game plan.',
  },
  {
    id: 'master-2400',
    label: 'Master Bot',
    elo: 2400,
    style: 'Technical and hard to beat',
    depth: 2,
    noise: 8,
    blunderChance: 0.006,
    description: 'For disciplined play and endgame conversion practice.',
  },
  {
    id: 'gm-sim-2800',
    label: 'Low-noise Alpha Trainer',
    elo: 2800,
    style: 'Low noise alpha engine',
    depth: 2,
    noise: 0,
    blunderChance: 0,
    description: 'Most consistent current minimax setting. The 2800 band is an aspirational practice label, not measured playing strength or Stockfish.',
  },
];

export const lessons: Lesson[] = [
  {
    id: 'rules-board-vision',
    title: 'Board Vision: stop leaving pieces behind',
    pillar: 'Pattern recognition',
    level: 'Complete beginner',
    minutes: 8,
    summary: 'Learn to scan every move for checks, captures, attacks, and loose pieces.',
    whyItMatters: 'Most early Elo is lost through one-move blunders. Before deep strategy, you need board safety.',
    drill: ['Before each move, say: checks, captures, threats.', 'Mark every undefended piece.', 'Play 5 moves against the 400 bot without hanging material.'],
    playerLink: 'Wesley So: solidity starts with not giving the opponent free targets.',
  },
  {
    id: 'forcing-lines',
    title: 'Calculation: three candidate moves',
    pillar: 'Calculation under pressure',
    level: '600–1200',
    minutes: 10,
    summary: 'Train the habit of choosing candidate moves before touching a piece.',
    whyItMatters: 'Caruana-style precision begins with refusing to move on vibes alone.',
    drill: ['Write or say three candidate moves.', 'Calculate the opponent’s best reply to each.', 'Only then choose your move.'],
    playerLink: 'Fabiano Caruana: calculation and preparation become one weapon.',
  },
  {
    id: 'equal-is-playable',
    title: 'Pressure from equal positions',
    pillar: 'Practical resilience',
    level: '1000–1800',
    minutes: 12,
    summary: 'Do not offer yourself a draw mentally just because the engine says equal.',
    whyItMatters: 'The research report’s Carlsen finding is practical pressure: keep useful tension alive.',
    drill: ['Improve your worst piece.', 'Create a second weakness.', 'Trade only when the resulting endgame is easier for you.'],
    playerLink: 'Magnus Carlsen: win by asking one more accurate question than the opponent can answer.',
  },
  {
    id: 'prep-as-force',
    title: 'Build a tiny opening file',
    pillar: 'Preparation and adaptability',
    level: '1200–2000',
    minutes: 15,
    summary: 'Create a simple opening repertoire that reaches playable positions you understand.',
    whyItMatters: 'Kasparov’s edge was not memorising moves. It was arriving first at positions he understood better.',
    drill: ['Pick one White opening and one Black response to e4 and d4.', 'For each, write the pawn structure goal.', 'Save one model game.'],
    playerLink: 'Garry Kasparov: preparation becomes force when it leads to initiative.',
  },
  {
    id: 'creative-imbalance',
    title: 'When to make the position strange',
    pillar: 'Adaptability',
    level: '1400–2200',
    minutes: 14,
    summary: 'Learn when an imbalance is worth more than a tiny engine-approved edge.',
    whyItMatters: 'Aronian shows that creativity can be rigorous: a strange position can make both players think independently.',
    drill: ['Name the imbalance: bishop pair, weak colour complex, space, king safety, pawn majority.', 'Ask who benefits from complexity.', 'Choose one move that keeps useful tension.'],
    playerLink: 'Levon Aronian: unusual ideas are strongest when they have positional roots.',
  },
];

export const puzzles: Puzzle[] = [
  {
    id: 'scholar-mate-finish',
    title: 'Punish the loose f7 square',
    motif: 'Mate in one',
    level: 'Beginner',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
    sideToMove: 'w',
    solution: ['h5f7'],
    hint: 'The black king is still in the centre and f7 is only defended by the king.',
    teachingPoint: 'Beginner attacks often start by noticing the weakest square near the uncastled king.',
  },
  {
    id: 'legal-mate',
    title: 'The classic smothered finish',
    motif: 'Back-rank pattern',
    level: 'Beginner+',
    fen: '6k1/5Qpp/8/8/8/8/6PP/6K1 w - - 0 1',
    sideToMove: 'w',
    solution: ['f7e8'],
    hint: 'Use the queen to take away the king’s final safe square.',
    teachingPoint: 'Mating patterns are pattern-recognition fuel. Learn the shape, not just the move.',
  },
  {
    id: 'win-hanging-queen',
    title: 'Remove the defender',
    motif: 'Tactical capture',
    level: 'Club',
    fen: 'rnb1kbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 1 3',
    sideToMove: 'w',
    solution: ['f3e5'],
    hint: 'A central pawn is undefended. Start by taking what is free.',
    teachingPoint: 'At lower levels, the best tactic is often simply noticing an undefended piece or pawn.',
  },
  {
    id: 'endgame-opposition',
    title: 'King activity first',
    motif: 'Endgame principle',
    level: 'Intermediate',
    fen: '8/8/8/8/3k4/8/3K4/8 w - - 0 1',
    sideToMove: 'w',
    solution: ['d2e2'],
    hint: 'In king endings, opposition and activity matter before pawns even appear.',
    teachingPoint: 'Carlsen-style endgame strength begins with loving king activity, not fearing simplified positions.',
  },
  {
    id: 'develop-with-tempo',
    title: 'Development with a threat',
    motif: 'Opening principle',
    level: 'Beginner+',
    fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
    sideToMove: 'w',
    solution: ['g1f3'],
    hint: 'Develop a piece and attack the centre at the same time.',
    teachingPoint: 'The app will teach openings as plans: develop, fight for the centre, castle, then improve.',
  },
];

export const watchCards: WatchCard[] = [
  {
    id: 'carlsen-squeeze',
    player: 'Magnus Carlsen',
    title: 'The equal position that was not equal in practice',
    idea: 'Carlsen’s games often teach that a position can be equal yet still uncomfortable.',
    positionLesson: 'Watch for small advantages: better king, healthier pawn structure, safer endgame, easier plan.',
    trainingTakeaway: 'In your games, do not rush. Improve one piece, create one weakness, then convert patiently.',
  },
  {
    id: 'kasparov-initiative',
    player: 'Garry Kasparov',
    title: 'Preparation becomes initiative',
    idea: 'Kasparov’s openings were not memory for its own sake. They created attacking momentum.',
    positionLesson: 'Opening prep should answer: what pawn break, what piece placement, what attacking target?',
    trainingTakeaway: 'Build tiny opening files around plans, not giant move trees.',
  },
  {
    id: 'caruana-machine',
    player: 'Fabiano Caruana',
    title: 'Calculate before the board explodes',
    idea: 'Caruana’s strength is seeing forcing lines clearly before committing.',
    positionLesson: 'When the centre can open, calculate captures and checks first.',
    trainingTakeaway: 'Use the three-candidate-move drill before every critical move.',
  },
  {
    id: 'aronian-imbalance',
    player: 'Levon Aronian',
    title: 'Creative imbalance without chaos',
    idea: 'Aronian’s creativity works because it is tied to real positional compensation.',
    positionLesson: 'A sacrifice or strange move needs a reason: activity, king safety, colour complex, or long-term pressure.',
    trainingTakeaway: 'Train yourself to name the compensation before choosing a creative move.',
  },
  {
    id: 'so-solidity',
    player: 'Wesley So',
    title: 'Solidity as a weapon',
    idea: 'So shows that calm, low-blunder chess can force opponents to overpress.',
    positionLesson: 'If you have no clear tactic, improve safety and ask the opponent to prove something.',
    trainingTakeaway: 'A quiet move that removes counterplay can be stronger than a flashy threat.',
  },
];

export const roadmapStages: RoadmapStage[] = [
  {
    band: '0–600',
    title: 'Learn the board and stop blunders',
    focus: 'Piece movement, legal moves, checkmate, board vision, basic material.',
    unlocks: ['400 bot', 'Mate-in-one puzzles', 'Board vision lesson'],
    habits: ['Say checks-captures-threats', 'Never move instantly', 'Castle before attacking'],
  },
  {
    band: '600–1000',
    title: 'Basic tactics and opening principles',
    focus: 'Forks, pins, skewers, hanging pieces, development, centre, king safety.',
    unlocks: ['800 bot', 'Beginner tactics pack', 'Opening principles lesson'],
    habits: ['Review every lost piece', 'Solve 5 puzzles daily', 'Play slow enough to think'],
  },
  {
    band: '1000–1400',
    title: 'Candidate moves and clean games',
    focus: 'Calculation habits, simple endgames, practical defence.',
    unlocks: ['1200 bot', 'Calculation trainer', 'Endgame basics'],
    habits: ['Three candidate moves', 'Analyse without engine first', 'Convert extra material calmly'],
  },
  {
    band: '1400–1800',
    title: 'Plans, pawn structures and resilience',
    focus: 'Pawn breaks, weak squares, good/bad pieces, defence under pressure.',
    unlocks: ['1600 bot', 'Carlsen pressure module', 'So solidity module'],
    habits: ['Name the plan', 'Improve worst piece', 'Defend worse positions stubbornly'],
  },
  {
    band: '1800–2200',
    title: 'Preparation and serious analysis',
    focus: 'Opening files, model games, endgame conversion, tournament routine.',
    unlocks: ['2000 bot', 'Kasparov prep module', 'Caruana calculation module'],
    habits: ['Maintain repertoire notes', 'Analyse losses deeply', 'Train physical stamina'],
  },
  {
    band: '2200+',
    title: 'Mastery track',
    focus: 'Opponent-specific prep, deep calculation, difficult technical wins, psychological durability.',
    unlocks: ['2400 and 2800 simulation bots', 'Advanced study rooms', 'GM-style review checklist'],
    habits: ['Build seconds-style notes', 'Play serious classical games', 'Balance creativity and risk control'],
  },
];
