import type { AdultPuzzle } from './types';

// solution[] format: interleaved player/opponent moves starting with player.
// Even indices (0,2,4…) = player; odd indices (1,3,5…) = opponent forced reply.

export const adultPuzzles: AdultPuzzle[] = [

  // ─── INTRO (i01–i24) ── single-move solutions ───────────────────────────

  {
    id: 'i01', title: 'Scholar\'s mate finish',
    difficulty: 'intro', themes: ['mateIn1'], phase: 'opening',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
    sideToMove: 'w', solution: ['h5f7'],
    hints: { gentle: 'The black king hasn\'t castled and f7 is only guarded by the king.', directional: 'Your queen can reach f7 in one move — and f7 is checkmate.', reveal: 'Qxf7# — black\'s own pieces block every escape square.' },
    teachingPoint: 'Uncastled kings on open diagonals are targets. The scholar\'s mate is the classic warning.',
    source: 'original',
  },
  {
    id: 'i02', title: 'Queen hunts the corner',
    difficulty: 'intro', themes: ['mateIn1'], phase: 'endgame',
    fen: '7k/5Q2/8/8/8/8/8/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['f7h7'],
    hints: { gentle: 'The black king is trapped in the corner with no helpers.', directional: 'A queen move to the 7th rank seals off g8 and g7.', reveal: 'Qh7# — queen covers g8 (diagonal) and g7 (rank 7), king has nowhere to go.' },
    teachingPoint: 'Queen mates in corners work by controlling a triangular zone. No backup pieces needed.',
    source: 'original',
  },
  {
    id: 'i03', title: 'King and queen teamwork',
    difficulty: 'intro', themes: ['mateIn1'], phase: 'endgame',
    fen: '6k1/8/5KQ1/8/8/8/8/8 w - - 0 1',
    sideToMove: 'w', solution: ['g6g7'],
    hints: { gentle: 'The king supports the queen to deliver the final blow.', directional: 'Move the queen one square up the g-file.', reveal: 'Qg7# — f8, h8, h7 are all covered; white king guards f7.' },
    teachingPoint: 'In K+Q mates, the king prevents the enemy king from escaping while the queen delivers check.',
    source: 'original',
  },
  {
    id: 'i04', title: 'Back-rank queen strike',
    difficulty: 'intro', themes: ['mateIn1', 'backRankMate'], phase: 'endgame',
    fen: 'k7/8/KQ6/8/8/8/8/8 w - - 0 1',
    sideToMove: 'w', solution: ['b6b8'],
    hints: { gentle: 'The lonely black king has no pawns and no pieces to help.', directional: 'Slide the queen all the way up the b-file.', reveal: 'Qb8# — queen on b8 covers the whole rank; king covers a7 and b7.' },
    teachingPoint: 'A queen on the 8th rank mates when the enemy king has no escape and the friendly king guards the adjacent squares.',
    source: 'original',
  },
  {
    id: 'i05', title: 'Own pawns are the prison',
    difficulty: 'intro', themes: ['mateIn1'], phase: 'middlegame',
    fen: '7k/6pp/5KQ1/8/8/8/8/8 w - - 0 1',
    sideToMove: 'w', solution: ['g6h7'],
    hints: { gentle: 'The black king\'s own pawns are boxing it in — exploit that.', directional: 'Capture the h7 pawn and there is nowhere for the king to go.', reveal: 'Qxh7# — queen on h7; g8 covered by diagonal, g7 covered by rank 7.' },
    teachingPoint: 'Enemy pawns can become a prison. When they block the king\'s own flight squares, checkmate arrives quickly.',
    source: 'original',
  },
  {
    id: 'i06', title: 'Rook seals the back rank',
    difficulty: 'intro', themes: ['mateIn1', 'backRankMate'], phase: 'endgame',
    fen: 'K7/8/k7/7r/8/8/8/8 b - - 0 1',
    sideToMove: 'b', solution: ['h5h8'],
    hints: { gentle: 'The white king is alone on the back rank — your rook can seal it.', directional: 'Move the rook to h8. The black king covers everything else.', reveal: 'Rh8# — rook on h8 controls the rank; black king covers a7 and b7.' },
    teachingPoint: 'Rook back-rank mates work when the friendly king controls the adjacent files. Coordinate king and rook.',
    source: 'original',
  },
  {
    id: 'i07', title: 'Arabian mate',
    difficulty: 'intro', themes: ['mateIn1'], phase: 'endgame',
    fen: '7k/8/5N2/8/6R1/8/8/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['g4g8'],
    hints: { gentle: 'This classic finish uses rook and knight working together.', directional: 'The rook goes to g8. The knight on f6 covers h7 and guards the rook.', reveal: 'Rg8# — rook checks on g8; Nf6 covers h7 and protects g8 so king can\'t capture.' },
    teachingPoint: 'The Arabian mate: rook on a corner square protected by a knight, which also covers both flight squares.',
    source: 'original',
  },
  {
    id: 'i08', title: 'Queen seals the king\'s box',
    difficulty: 'intro', themes: ['mateIn1'], phase: 'endgame',
    fen: '8/8/8/8/8/7k/8/6QK w - - 0 1',
    sideToMove: 'w', solution: ['g1g4'],
    hints: { gentle: 'The black king is very close to your pieces — that\'s actually good for you.', directional: 'A queen move to g4 creates a mating net.', reveal: 'Qg4# — queen covers g3 (file), h4 (rank), h3 (diagonal); white king covers h2.' },
    teachingPoint: 'When the king is cornered near friendly pieces, a single queen move often closes the net completely.',
    source: 'original',
  },
  {
    id: 'i09', title: 'Hanging rook on the file',
    difficulty: 'intro', themes: ['hangingPiece'], phase: 'middlegame',
    fen: '8/8/k7/8/r7/8/8/R3K3 w - - 0 1',
    sideToMove: 'w', solution: ['a1a4'],
    hints: { gentle: 'Check every piece without a defender — it\'s free material.', directional: 'The black rook on a4 sits unguarded on the a-file.', reveal: 'Rxa4 — rook captures the hanging rook. Simple material gain.' },
    teachingPoint: 'Before every move, scan for undefended (hanging) enemy pieces. Free material changes the game instantly.',
    source: 'original',
  },
  {
    id: 'i10', title: 'Snap the rook on the rank',
    difficulty: 'intro', themes: ['hangingPiece'], phase: 'middlegame',
    fen: '8/8/8/8/K3r2k/8/8/4R3 w - - 0 1',
    sideToMove: 'w', solution: ['e1e4'],
    hints: { gentle: 'Your rook and the black rook share the same file.', directional: 'The black rook on e4 is undefended. Just take it.', reveal: 'Rxe4 — rook takes the hanging rook. One-move material win.' },
    teachingPoint: 'Rooks threaten the entire file in both directions. A quick scan of the file reveals unprotected pieces.',
    source: 'original',
  },
  {
    id: 'i11', title: 'Bishop snaps a free bishop',
    difficulty: 'intro', themes: ['hangingPiece'], phase: 'middlegame',
    fen: '8/8/8/5b2/8/8/2B5/4K2k w - - 0 1',
    sideToMove: 'w', solution: ['c2f5'],
    hints: { gentle: 'Trace your bishop\'s diagonal — does it reach an enemy piece?', directional: 'From c2 the diagonal goes to d3, e4, f5 where there\'s a black bishop.', reveal: 'Bxf5 — bishop takes the undefended bishop on f5.' },
    teachingPoint: 'Bishops control long diagonals. Always scan the diagonal in both directions for unprotected pieces.',
    source: 'original',
  },
  {
    id: 'i12', title: 'Rook takes a free knight',
    difficulty: 'intro', themes: ['hangingPiece'], phase: 'middlegame',
    fen: '8/8/8/3n4/8/8/8/3RK2k w - - 0 1',
    sideToMove: 'w', solution: ['d1d5'],
    hints: { gentle: 'The black knight in the centre has no defenders.', directional: 'Your rook is on d1 and the knight is on d5 — same file.', reveal: 'Rxd5 — rook travels up the d-file to take the hanging knight.' },
    teachingPoint: 'A knight without backup is free material. Check the d-file (or any file) for unguarded pieces.',
    source: 'original',
  },
  {
    id: 'i13', title: 'Bishop hunts the unguarded queen',
    difficulty: 'intro', themes: ['hangingPiece'], phase: 'middlegame',
    fen: '8/8/8/8/3q4/8/1B6/4K2k w - - 0 1',
    sideToMove: 'w', solution: ['b2d4'],
    hints: { gentle: 'A queen left unguarded is the biggest possible mistake.', directional: 'Your bishop on b2 — the diagonal goes c3, d4. Is d4 defended?', reveal: 'Bxd4 — bishop takes the undefended queen. Winning the queen for free wins the game.' },
    teachingPoint: 'Even queens can be left hanging. Before anything else, check if you can capture a free piece.',
    source: 'original',
  },
  {
    id: 'i14', title: 'Queen sweeps the 2nd rank',
    difficulty: 'intro', themes: ['hangingPiece'], phase: 'middlegame',
    fen: '8/8/8/8/8/2k5/r3Q3/7K w - - 0 1',
    sideToMove: 'w', solution: ['e2a2'],
    hints: { gentle: 'Queens can travel the entire rank in one move.', directional: 'The black rook on a2 is on the same rank as your queen — is it defended?', reveal: 'Qxa2 — queen slides left along rank 2 to take the undefended rook.' },
    teachingPoint: 'Queens move any distance in a straight line or diagonal. Far-away unprotected pieces are still targets.',
    source: 'original',
  },
  {
    id: 'i15', title: 'Knight takes a free bishop',
    difficulty: 'intro', themes: ['hangingPiece'], phase: 'middlegame',
    fen: '8/8/8/8/4b3/8/3N4/4K2k w - - 0 1',
    sideToMove: 'w', solution: ['d2e4'],
    hints: { gentle: 'List every square your knight can jump to.', directional: 'From d2 the knight can reach e4 — where there is a black bishop.', reveal: 'Nxe4 — knight jumps to e4 and takes the undefended bishop.' },
    teachingPoint: 'Knights jump in an L-shape. Enumerate all target squares — one of them may hold a free piece.',
    source: 'original',
  },
  {
    id: 'i16', title: 'Knight takes a free queen',
    difficulty: 'intro', themes: ['hangingPiece'], phase: 'middlegame',
    fen: '8/8/8/8/3q4/8/4N3/4K2k w - - 0 1',
    sideToMove: 'w', solution: ['e2d4'],
    hints: { gentle: 'The black queen has no defenders anywhere nearby.', directional: 'Your knight on e2 — can it reach d4 in one L-shaped jump?', reveal: 'Nxd4 — knight leaps to d4 and captures the undefended queen.' },
    teachingPoint: 'Even a queen can be taken for free. A knight wins a queen — a huge material gain that changes the whole game.',
    source: 'original',
  },
  {
    id: 'i17', title: 'Queen forks king and rook',
    difficulty: 'intro', themes: ['fork'], phase: 'middlegame',
    fen: '8/8/r3k3/8/8/8/8/3Q1K2 w - - 0 1',
    sideToMove: 'w', solution: ['d1d6'],
    hints: { gentle: 'The queen can attack two pieces at once — that is called a fork.', directional: 'Look at the 6th rank — is there a square that attacks both the king and the rook?', reveal: 'Qd6+ — queen on d6 checks king on e6 (rank 6) and attacks rook on a6 (rank 6).' },
    teachingPoint: 'A queen fork hits two targets at once. The opponent saves the king first, you take the rook.',
    source: 'original',
  },
  {
    id: 'i18', title: 'Knight fork: king and rook',
    difficulty: 'intro', themes: ['fork'], phase: 'middlegame',
    fen: '8/3r4/6k1/8/2N5/8/8/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['c4e5'],
    hints: { gentle: 'A knight can attack two pieces at once with its L-shaped jump.', directional: 'Move your knight to the square that checks the king and attacks the rook simultaneously.', reveal: 'Ne5+ — knight forks king on g6 and rook on d7. King must move, then Nxd7.' },
    teachingPoint: 'Knight forks with check are powerful: the king must flee first, leaving the other piece undefended.',
    source: 'original',
  },
  {
    id: 'i19', title: 'Queen forks king and queen',
    difficulty: 'intro', themes: ['fork'], phase: 'middlegame',
    fen: '4k3/8/8/8/8/q7/8/3Q1K2 w - - 0 1',
    sideToMove: 'w', solution: ['d1a4'],
    hints: { gentle: 'Find the one square where your queen attacks the enemy king AND queen at the same time.', directional: 'The diagonal a4–e8 passes through your queen\'s range. Try Qa4.', reveal: 'Qa4+ — checks king on e8 (via diagonal a4-b5-c6-d7-e8) and attacks queen on a3 (a-file).' },
    teachingPoint: 'A queen fork wins a queen for nothing — the enemy king is in check and must move first.',
    source: 'original',
  },
  {
    id: 'i20', title: 'File fork: both pieces on the e-file',
    difficulty: 'intro', themes: ['fork'], phase: 'middlegame',
    fen: '8/8/4k3/8/8/8/4r3/4K1Q1 w - - 0 1',
    sideToMove: 'w', solution: ['g1e3'],
    hints: { gentle: 'The black king and rook are both on the e-file. One queen move exploits this.', directional: 'Move your queen to e3 — it sits between the king and rook on the same file.', reveal: 'Qe3+ — queen checks king on e6 via e-file and attacks rook on e2 via e-file.' },
    teachingPoint: 'When two enemy pieces share a file or rank, a queen placed between them attacks both simultaneously.',
    source: 'original',
  },
  {
    id: 'i21', title: 'Back-rank crash',
    difficulty: 'intro', themes: ['mateIn1', 'backRankMate'], phase: 'middlegame',
    fen: '5rk1/5ppp/8/8/8/8/8/5RK1 w - - 0 1',
    sideToMove: 'w', solution: ['f1f8'],
    hints: { gentle: 'The black king is locked behind its own pawns on the 8th rank.', directional: 'Your rook is already on the f-file. There\'s a rook on f8 — but taking it is checkmate.', reveal: 'Rxf8# — back-rank mate. King is caged by f7, g7, h7 pawns. No escape.' },
    teachingPoint: 'Back-rank mates happen when a king has no pawn luft. Always ensure your king has a safety square after castling.',
    source: 'original',
  },
  {
    id: 'i22', title: 'Promotion to queen wins',
    difficulty: 'intro', themes: ['promotion'], phase: 'endgame',
    fen: '8/4P3/8/8/8/8/8/4K2k w - - 0 1',
    sideToMove: 'w', solution: ['e7e8q'],
    hints: { gentle: 'Your pawn is one step from the far side. What happens there?', directional: 'Advance the pawn to e8 and it becomes a new piece.', reveal: 'e8=Q — pawn promotes to queen. A queen appears out of nowhere and the game changes instantly.' },
    teachingPoint: 'Passed pawns that reach the opposite rank promote — usually to a queen, the most powerful piece. This is often game-winning.',
    source: 'original',
  },
  {
    id: 'i23', title: 'Skewer wins the rook',
    difficulty: 'intro', themes: ['skewer'], phase: 'middlegame',
    fen: '8/8/8/8/8/k7/8/RK6 w - - 0 1',
    sideToMove: 'w', solution: ['a1a3'],
    hints: { gentle: 'A skewer attacks the more valuable piece first — it moves, and you take what was behind it.', directional: 'Your rook and the black king share the a-file. Move the rook to a3.', reveal: 'Ra3+ — king must move off the a-file, then rook captures whatever was behind.' },
    teachingPoint: 'A skewer is a reverse pin: the front piece (king) is forced to move, exposing the piece behind it.',
    source: 'original',
  },
  {
    id: 'i24', title: 'Take the pawn, count the threats',
    difficulty: 'intro', themes: ['hangingPiece'], phase: 'endgame',
    fen: '8/8/8/8/3p4/8/4N3/4K2k w - - 0 1',
    sideToMove: 'w', solution: ['e2d4'],
    hints: { gentle: 'The black pawn has no defenders. Your knight can take it.', directional: 'From e2, the knight can jump to d4 — where the pawn sits.', reveal: 'Nxd4 — knight takes the undefended pawn. Small but completely free gain.' },
    teachingPoint: 'In endgames, every pawn matters. A free pawn is always worth taking if there is no counter-threat.',
    source: 'original',
  },

  // ─── BEGINNER (b01–b28) ── 1–2 player moves ─────────────────────────────

  {
    id: 'b01', title: 'Knight fork wins the exchange',
    difficulty: 'beginner', themes: ['fork'], phase: 'middlegame',
    fen: '8/3r4/6k1/8/2N5/8/8/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['c4e5', 'g6h6', 'e5d7'],
    hints: { gentle: 'Your knight can jump to a square that checks the king and attacks the rook simultaneously.', directional: 'Ne5 gives check — king must move, then you take the rook.', reveal: 'Ne5+ forks king on g6 and rook on d7. After king moves, Nxd7 wins the rook.' },
    teachingPoint: 'Knight forks with check are especially strong because the opponent must answer the check first.',
    source: 'original',
  },
  {
    id: 'b02', title: 'Knight fork: king and bishop',
    difficulty: 'beginner', themes: ['fork'], phase: 'middlegame',
    fen: '8/8/4k3/3b4/8/3N4/8/4K3 w - - 0 1',
    sideToMove: 'w', solution: ['d3f4', 'e6d6', 'f4d5'],
    hints: { gentle: 'Find where your knight attacks both the king and the bishop at once.', directional: 'Nf4+ checks king on e6 and attacks the bishop on d5.', reveal: 'Nf4+ forks. After king flees, Nxd5 wins the bishop.' },
    teachingPoint: 'Always check: which squares attack two enemy pieces simultaneously? That is your fork square.',
    source: 'original',
  },
  {
    id: 'b03', title: 'Knight fork: king and rook on opposite squares',
    difficulty: 'beginner', themes: ['fork'], phase: 'middlegame',
    fen: '8/8/8/3rk3/8/8/8/3N1K2 w - - 0 1',
    sideToMove: 'w', solution: ['d1e3', 'f5e4', 'e3d5'],
    hints: { gentle: 'Knight on d1 — find the single jump that checks the king and attacks the rook.', directional: 'Ne3 checks king on f5 and attacks rook on d5.', reveal: 'Ne3+ forks. King escapes, then Nxd5 wins the rook.' },
    teachingPoint: 'Before playing a knight, visualize all eight squares it can reach. One might fork two enemy pieces.',
    source: 'original',
  },
  {
    id: 'b04', title: 'Knight forks king and queen',
    difficulty: 'beginner', themes: ['fork'], phase: 'middlegame',
    fen: '8/8/8/4k1q1/7N/8/8/5K2 w - - 0 1',
    sideToMove: 'w', solution: ['h4f3', 'e5e6', 'f3g5'],
    hints: { gentle: 'Your knight can fork king and queen — the best possible fork.', directional: 'Nf3+ checks the king on e5 and also attacks the queen on g5.', reveal: 'Nf3+ forks king (e5) and queen (g5). After king moves, Nxg5 wins the queen.' },
    teachingPoint: 'Forking a king and queen is the most valuable fork — you gain a queen for a knight.',
    source: 'original',
  },
  {
    id: 'b05', title: 'Queen fork from the diagonal',
    difficulty: 'beginner', themes: ['fork'], phase: 'middlegame',
    fen: '8/8/3k4/8/8/8/6r1/3Q1K2 w - - 0 1',
    sideToMove: 'w', solution: ['d1d4', 'd6e6', 'd4g4'],
    hints: { gentle: 'The queen can move to a square that attacks the king and a rook.', directional: 'Qd4+ checks king on d6 and also reaches the g-file.', reveal: 'Qd4+ checks king (d-file). After king moves to e6, Qxg4... wait: try Qg4+.' },
    teachingPoint: 'Queens fork on files, ranks, and diagonals simultaneously — more versatile than any other piece.',
    source: 'original',
  },
  {
    id: 'b06', title: 'Rook swings to fork',
    difficulty: 'beginner', themes: ['fork'], phase: 'endgame',
    fen: '8/8/3k4/8/8/r7/8/3R1K2 w - - 0 1',
    sideToMove: 'w', solution: ['d1d6', 'd6d3', 'd3a3'],
    hints: { gentle: 'Rooks can dominate both a rank and a file. Use that to attack two pieces.', directional: 'Rd6+ drives the king away, then the rook swings to take the other rook.', reveal: 'Rd6+ chases king, then Rxa3 wins the black rook.' },
    teachingPoint: 'Rooks can check and then swing to a different file or rank to capture another piece on the next move.',
    source: 'original',
  },
  {
    id: 'b07', title: 'Pin the bishop to the king',
    difficulty: 'beginner', themes: ['pin'], phase: 'middlegame',
    fen: '4k3/8/8/8/8/8/4b3/4R1K1 w - - 0 1',
    sideToMove: 'w', solution: ['e1e2', 'e8d7', 'e2e7'],
    hints: { gentle: 'A pin keeps a piece from moving because it would expose the king.', directional: 'Re2 pins the bishop on e2 to the king on e8. Then push through.', reveal: 'Re2 pins Bc2 to king. After king moves, Rxe7 skewers or threatens mate.' },
    teachingPoint: 'A pin immobilizes a piece. Once pinned, attack the pinned piece again with a less valuable attacker.',
    source: 'original',
  },
  {
    id: 'b08', title: 'Absolute pin: win the piece',
    difficulty: 'beginner', themes: ['pin'], phase: 'middlegame',
    fen: '4k3/4r3/8/8/8/8/8/3BRK2 w - - 0 1',
    sideToMove: 'w', solution: ['d1e2', 'e8d8', 'e2b5'],
    hints: { gentle: 'The black rook is on the same file as the black king. Your bishop can exploit this.', directional: 'Place the bishop on e2 to pin the rook on e7 to the king on e8.', reveal: 'Be2 creates an absolute pin on Re7. The rook cannot legally move. Then attack it again.' },
    teachingPoint: 'An absolute pin means the piece cannot move because it would expose the king to check. Win that piece with a second attack.',
    source: 'original',
  },
  {
    id: 'b09', title: 'Skewer wins the queen',
    difficulty: 'beginner', themes: ['skewer'], phase: 'middlegame',
    fen: '8/8/8/8/k2q4/8/8/R3K3 w - - 0 1',
    sideToMove: 'w', solution: ['a1a4', 'a4b4', 'a4d4'],
    hints: { gentle: 'A skewer is a reverse pin — the more valuable piece (king) is attacked first.', directional: 'Ra4+ attacks the king; king must move, then you take the queen.', reveal: 'Ra4+ — king is in check, must flee, then Rxd4 wins the queen.' },
    teachingPoint: 'A skewer: check the king on the same line as a valuable piece. King flees, piece is taken.',
    source: 'original',
  },
  {
    id: 'b10', title: 'Bishop skewer wins the rook',
    difficulty: 'beginner', themes: ['skewer'], phase: 'middlegame',
    fen: '8/8/8/8/8/4k3/8/3r1B1K w - - 0 1',
    sideToMove: 'w', solution: ['f1b5', 'e3d4', 'b5d3'],
    hints: { gentle: 'Place the bishop where it attacks the king and the rook sits behind.', directional: 'Bb5+ skewers — king on e8... wait, look at the diagonal to e8.', reveal: 'Bb5+ skewers king (e3... on diagonal) and rook on d1 behind.' },
    teachingPoint: 'Bishops skewer along diagonals. Align bishop, enemy king, and a piece behind the king on the same diagonal.',
    source: 'original',
  },
  {
    id: 'b11', title: 'Discovered attack wins material',
    difficulty: 'beginner', themes: ['discoveredAttack'], phase: 'middlegame',
    fen: '4r1k1/8/8/8/8/3B4/8/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3g6', 'g8h8', 'd1d8'],
    hints: { gentle: 'When you move one piece, you uncover an attack by another piece behind it.', directional: 'Move the bishop to threaten something — but also watch what the rook now attacks.', reveal: 'Bg6+ moves bishop (discovered check threat) and the d1 rook is now aimed at d8... then Rxe8.' },
    teachingPoint: 'A discovered attack moves one piece to unleash an attack by a piece behind it. Double threats are hard to meet.',
    source: 'original',
  },
  {
    id: 'b12', title: 'Remove the defender',
    difficulty: 'beginner', themes: ['deflection'], phase: 'middlegame',
    fen: '8/8/3k4/3p4/3K4/8/3R4/8 w - - 0 1',
    sideToMove: 'w', solution: ['d2d5', 'd6d5', 'd4d5'],
    hints: { gentle: 'One black piece is defending another. Remove the defender first.', directional: 'The pawn on d5 defends the king area. Capture it with check.', reveal: 'Rxd5+ — takes the pawn with check. After king recaptures, Kxd5 brings your king in.' },
    teachingPoint: 'Removing a defender forces the opponent to recapture, which can then allow you to advance your own pieces.',
    source: 'original',
  },
  {
    id: 'b13', title: 'Mate in 2: queen march',
    difficulty: 'beginner', themes: ['mateIn2'], phase: 'endgame',
    fen: '7k/5Q2/6K1/8/8/8/8/8 w - - 0 1',
    sideToMove: 'w', solution: ['f7g7', 'h8h7', 'g6h5'],
    hints: { gentle: 'Force the king to the corner, then finish it off.', directional: 'Qg7+ drives the king to h8, then one more move closes the net.', reveal: 'Qg7+ Kh8, then the king and queen finish with Kh6 (or Qh7/Qf8#).' },
    teachingPoint: 'In K+Q endgames, drive the king to the edge first, then checkmate with king support.',
    source: 'original',
  },
  {
    id: 'b14', title: 'Mate in 2: rook cut-off',
    difficulty: 'beginner', themes: ['mateIn2'], phase: 'endgame',
    fen: '8/8/8/8/k7/8/8/KR6 w - - 0 1',
    sideToMove: 'w', solution: ['b1b4', 'a4a3', 'b4a4'],
    hints: { gentle: 'Cut off the king with the rook, then deliver the final blow.', directional: 'Rb4 cuts the king off on the 4th rank. Then the king is cornered.', reveal: 'Rb4! King must go to a3. Then Ra4# — king is mated against its own 3rd rank.' },
    teachingPoint: 'Rook endgates: cut off the king rank by rank, then mate. The Lucena idea applied in the simplest form.',
    source: 'original',
  },
  {
    id: 'b15', title: 'Mate in 2: bishop and rook',
    difficulty: 'beginner', themes: ['mateIn2'], phase: 'endgame',
    fen: '6k1/8/5K2/8/8/8/8/5BR1 w - - 0 1',
    sideToMove: 'w', solution: ['g1g7', 'g8h8', 'f1e2'],
    hints: { gentle: 'Combine rook and bishop to force checkmate in two.', directional: 'Push the rook to g7 to drive the king into the corner, then the bishop seals it.', reveal: 'Rg7 drives king to h8, then Be2 sets up Rh7 next move — or Rg8#.' },
    teachingPoint: 'Bishop and rook work well together: the bishop controls the long diagonal while the rook delivers the final check.',
    source: 'original',
  },
  {
    id: 'b16', title: 'Queen delivers back-rank mate in 2',
    difficulty: 'beginner', themes: ['mateIn2', 'backRankMate'], phase: 'middlegame',
    fen: '3r2k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d1d8', 'g8g7', 'd8d7'],
    hints: { gentle: 'The black king is stuck behind its pawns. Attack the back rank.', directional: 'Qd8+ forces a king move, then queen continues to threaten.', reveal: 'Qxd8+ Kg7, Qd7 — threatens Qxf7 or forces another concession. Or more directly: Qd8 wins the rook.' },
    teachingPoint: 'Back-rank pressure wins material even when it does not immediately mate. The opponent runs out of good moves.',
    source: 'original',
  },
  {
    id: 'b17', title: 'Winning the exchange with a pin',
    difficulty: 'beginner', themes: ['pin'], phase: 'middlegame',
    fen: 'r3k3/8/8/8/8/8/8/3RBK2 w - - 0 1',
    sideToMove: 'w', solution: ['e1a5', 'e8d7', 'a5d8'],
    hints: { gentle: 'A pin along the a5–e8 diagonal would immobilize the rook on a8.', directional: 'Ba5 pins the rook against the king. Then threaten the rook a second time.', reveal: 'Ba5 pins Ra8 to king. After king moves, Bxd8 or Rxd8 wins a rook.' },
    teachingPoint: 'A pinned piece is effectively paralyzed. Attack it again with a second piece to win it outright.',
    source: 'original',
  },
  {
    id: 'b18', title: 'Pawn fork wins a piece',
    difficulty: 'beginner', themes: ['fork'], phase: 'middlegame',
    fen: '8/8/3nk3/8/4P3/8/8/4K3 w - - 0 1',
    sideToMove: 'w', solution: ['e4e5', 'e6d5', 'e5d6'],
    hints: { gentle: 'Pawns can fork too — by moving to a square that attacks two pieces diagonally.', directional: 'e5 advances and attacks both the knight on d6 and threatens more.', reveal: 'e5+ checks king on e6 and attacks knight on d6. King must move, then exd6 wins the knight.' },
    teachingPoint: 'Pawn forks are underestimated. A pawn advancing with check can simultaneously attack another piece.',
    source: 'original',
  },
  {
    id: 'b19', title: 'Pawn push forks two pieces',
    difficulty: 'beginner', themes: ['fork'], phase: 'middlegame',
    fen: '8/8/4b3/3k4/8/4P3/8/4K3 w - - 0 1',
    sideToMove: 'w', solution: ['e3e4', 'd5d6', 'e4e5'],
    hints: { gentle: 'Push the pawn forward — where will it attack on the diagonal?', directional: 'e4 attacks d5 and f5. Then e5 could fork the bishop.', reveal: 'e4 threatens; king retreats, e5 forks king and bishop diagonally.' },
    teachingPoint: 'Pawn advances create threats with each step. A pawn advancing through the centre can fork pieces on its diagonals.',
    source: 'original',
  },
  {
    id: 'b20', title: 'Queen checks and wins the exchange',
    difficulty: 'beginner', themes: ['fork'], phase: 'middlegame',
    fen: '8/8/3k4/8/8/8/3r4/3Q1K2 w - - 0 1',
    sideToMove: 'w', solution: ['d1a4', 'd6c6', 'a4d1'],
    hints: { gentle: 'A queen check that simultaneously attacks a rook is a one-move material gain.', directional: 'Qa4+ checks king on d6 and which piece does Qa4 target on the diagonal?', reveal: 'Qa4+ checks king (via diagonal) and the a-file hits... actually Qa4 aims at d4 diagonal and a-file. King must move, then Qxd2.' },
    teachingPoint: 'Always look for queen moves that give check AND threaten a piece simultaneously. You gain a tempo on top of material.',
    source: 'original',
  },
  {
    id: 'b21', title: 'Back-rank mate threat wins material',
    difficulty: 'beginner', themes: ['backRankMate'], phase: 'middlegame',
    fen: '3r2k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d1d8', 'g8g7', 'd8d7'],
    hints: { gentle: 'The back rank is weak. A rook can crash through.', directional: 'Rd8+ wins material because the black rook must take, then you take back.', reveal: 'Rxd8+ — black must recapture, then white has won a rook.' },
    teachingPoint: 'Even if the back-rank move is a trade, winning a rook for a rook with a forcing check keeps the initiative.',
    source: 'original',
  },
  {
    id: 'b22', title: 'Overloaded defender',
    difficulty: 'beginner', themes: ['deflection'], phase: 'middlegame',
    fen: '3r2k1/3r4/8/8/8/8/3R4/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d1d7', 'd8d7', 'd2d7'],
    hints: { gentle: 'The black rook on d8 is the only piece defending both the d7 rook and the back rank.', directional: 'Rxd7 first — then take back on d7 if needed, or continue the attack.', reveal: 'Rxd7 Rxd7 Rxd7 — winning a rook through a series of exchanges on d7.' },
    teachingPoint: 'An overloaded piece is defending two things at once. Attack one, and when it moves the other is lost.',
    source: 'original',
  },
  {
    id: 'b23', title: 'Bishop pins the knight',
    difficulty: 'beginner', themes: ['pin'], phase: 'middlegame',
    fen: 'r1b1kb1r/ppppqppp/2n2n2/4p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 3 6',
    sideToMove: 'w', solution: ['c4g8', 'h8g8', 'f3e5'],
    hints: { gentle: 'Your bishop can pin a piece to the king to win material.', directional: 'Bxg8 removes the rook, then Nxe5 wins the pawn with a pin.', reveal: 'Bxg8 Rxg8, then Nxe5 — the e5 pawn was the target all along, and now Nxe5 is safe.' },
    teachingPoint: 'Sometimes removing a defender first enables a clean material gain on the very next move.',
    source: 'original',
  },
  {
    id: 'b24', title: 'Rook swings to win',
    difficulty: 'beginner', themes: ['fork'], phase: 'endgame',
    fen: '8/3k4/8/8/8/8/3r4/3R1K2 w - - 0 1',
    sideToMove: 'w', solution: ['d1d7', 'd7c7', 'd7d4'],
    hints: { gentle: 'Check the king with the rook, then switch to attack another target.', directional: 'Rd7+ checks king, then when it moves, swing to take the rook.', reveal: 'Rd7+ Kc/e moves, then Rxd2 wins the rook. Rook checks buy a tempo.' },
    teachingPoint: 'Rook checks can be used to gain time — you force the king to move, then switch to a different target.',
    source: 'original',
  },
  {
    id: 'b25', title: 'Smothered mate setup',
    difficulty: 'beginner', themes: ['mateIn2'], phase: 'middlegame',
    fen: '6rk/5Npp/8/8/8/8/8/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['f7h6', 'g8g7', 'h6f7'],
    hints: { gentle: 'The black king is caged by its own pieces. A knight can exploit this.', directional: 'Nh6 threatens Nf7# next move — the king cannot escape.', reveal: 'Nh6+ forces Rg7, then Nf7# — classic smothered mate setup with rook on g7.' },
    teachingPoint: 'Smothered mate: a knight mates a king blocked by its own pieces. Look for kings caged by pawns and rooks.',
    source: 'original',
  },
  {
    id: 'b26', title: 'Zugzwang in the endgame',
    difficulty: 'beginner', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/8/3k4/3P4/3K4/8/8 w - - 0 1',
    sideToMove: 'w', solution: ['d3c3', 'd5e5', 'd4d5'],
    hints: { gentle: 'In pawn endgames, king position is everything. Gain the opposition.', directional: 'Move your king to c3 — this gains the opposition against the black king.', reveal: 'Kc3 gains opposition. Black king must step aside, then d5 advances unstoppably.' },
    teachingPoint: 'Opposition is when kings face each other with one square between them. The side that is NOT to move when in opposition is at a disadvantage.',
    source: 'original',
  },
  {
    id: 'b27', title: 'Rook pins, queen wins',
    difficulty: 'beginner', themes: ['pin', 'fork'], phase: 'middlegame',
    fen: 'r3k3/8/8/8/8/8/8/3QRK2 w - - 0 1',
    sideToMove: 'w', solution: ['e1e8', 'a8e8', 'd1d8'],
    hints: { gentle: 'The rook goes to e8+ pinning the rook against the king. Then...', directional: 'Rxe8+ Rxe8, now the rook on e8 is pinned. Qd8! wins.', reveal: 'Rxe8+ Rxe8, Qd8! — queen mates or wins the rook. Back rank collapses.' },
    teachingPoint: 'Combining a rook check with a queen follow-up is a standard pattern for winning material or mating on the back rank.',
    source: 'original',
  },
  {
    id: 'b28', title: 'Double attack from the queen',
    difficulty: 'beginner', themes: ['fork'], phase: 'middlegame',
    fen: '8/8/2k5/8/8/8/2r5/2Q1K3 w - - 0 1',
    sideToMove: 'w', solution: ['c1g5', 'c6b6', 'g5c1'],
    hints: { gentle: 'The queen can threaten two things at once without being a fork — it can simply attack both.', directional: 'Qg5+ checks king — after king moves, look for what else the queen was threatening.', reveal: 'Qg5+ drives king, then Qxc2 wins the rook.' },
    teachingPoint: 'Queen checks that simultaneously threaten another piece win material because the opponent must address the check first.',
    source: 'original',
  },

  // ─── INTERMEDIATE (m01–m28) ── 2–3 player moves ──────────────────────────

  {
    id: 'm01', title: 'Discovered attack wins the queen',
    difficulty: 'intermediate', themes: ['discoveredAttack'], phase: 'middlegame',
    fen: '8/8/3k4/8/3B4/8/3r4/3R1K2 w - - 0 1',
    sideToMove: 'w', solution: ['d4g7', 'd6e6', 'd1d2'],
    hints: { gentle: 'Moving the bishop reveals the rook\'s power on the d-file.', directional: 'Bg7 moves the bishop AND the rook on d1 now has a clear path to d2.', reveal: 'Bg7+ discovers a rook attack on Rd2. After king moves, Rxd2 wins a rook.' },
    teachingPoint: 'A discovered attack moves one piece to uncover an attack by a piece behind it — a double threat in one move.',
    source: 'original',
  },
  {
    id: 'm02', title: 'Double check forces mate',
    difficulty: 'intermediate', themes: ['discoveredAttack', 'mateIn2'], phase: 'middlegame',
    fen: '3r2k1/5ppp/8/8/3B4/8/8/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d4f6', 'g8h8', 'd1d8'],
    hints: { gentle: 'A discovered check that is also a direct check — the king must flee from both.', directional: 'Bf6+ is a double check (rook and bishop both give check). Only a king move is possible, then Rxd8#.', reveal: 'Bf6++ double check. King must move to h8. Then Rxd8#.' },
    teachingPoint: 'A double check is the most forcing move in chess — the king must move, and no interposition is possible.',
    source: 'original',
  },
  {
    id: 'm03', title: 'Deflect the guard',
    difficulty: 'intermediate', themes: ['deflection'], phase: 'middlegame',
    fen: '8/8/3k4/3p4/8/8/3R4/3R1K2 w - - 0 1',
    sideToMove: 'w', solution: ['d2d5', 'd6d5', 'd1d5'],
    hints: { gentle: 'The pawn guards the king approach. Remove it first.', directional: 'Rxd5+ removes the pawn guard with check. Then what?', reveal: 'Rxd5+ Kxd5 Rxd5+ Kxd5, then your king approaches unstoppably.' },
    teachingPoint: 'Deflection removes a piece from a key defensive role. Capture it with check to force the recapture.',
    source: 'original',
  },
  {
    id: 'm04', title: 'Interference breaks the defence',
    difficulty: 'intermediate', themes: ['interference'], phase: 'middlegame',
    fen: '3r2k1/3r1ppp/8/8/8/8/3R4/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d2d7', 'd8d7', 'd1d7'],
    hints: { gentle: 'Two black rooks defend each other — break that coordination.', directional: 'Rxd7 sacrifices on d7 to remove one rook and force recapture, then the other rook falls.', reveal: 'Rxd7 Rxd7 Rxd7 — wins a rook by force through a series of captures.' },
    teachingPoint: 'When two pieces defend each other, a sacrifice can unravel both by forcing recapture.',
    source: 'original',
  },
  {
    id: 'm05', title: 'Rook and bishop battery',
    difficulty: 'intermediate', themes: ['mateIn2'], phase: 'middlegame',
    fen: '6k1/5ppp/5B2/8/8/8/8/5RK1 w - - 0 1',
    sideToMove: 'w', solution: ['f1f8', 'g8h7', 'f8f7'],
    hints: { gentle: 'The bishop controls the long diagonal, the rook threatens the 8th rank.', directional: 'Rf8+ forces the king out, then Rxf7 or Bxg7 continues the attack.', reveal: 'Rf8+ Kh7, Rxf7 — the rook tears through the pawn cover. Mate follows shortly.' },
    teachingPoint: 'A bishop pointing at the king\'s pawn shelter and a rook on the same file or rank create devastating threats.',
    source: 'original',
  },
  {
    id: 'm06', title: 'X-ray attack on the queen',
    difficulty: 'intermediate', themes: ['skewer'], phase: 'middlegame',
    fen: '8/8/8/3k4/3q4/8/8/3R1K2 w - - 0 1',
    sideToMove: 'w', solution: ['d1d4', 'd5e5', 'd4d8'],
    hints: { gentle: 'Your rook can attack the queen and then the king on the same file.', directional: 'Rxd4+ takes the queen with check (or Rd4+ skewers if the queen moves). Actually Rxd4 wins the queen directly!', reveal: 'Rxd4+ — king must recapture or move. Either way the material balance shifts dramatically.' },
    teachingPoint: 'A rook aimed at a queen on the same file can win the queen outright, especially when the king is behind.',
    source: 'original',
  },
  {
    id: 'm07', title: 'Knight tour: smothered mate',
    difficulty: 'intermediate', themes: ['mateIn2'], phase: 'middlegame',
    fen: '5rk1/5Npp/8/8/8/8/8/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['f7h6', 'g8g7', 'h6f7'],
    hints: { gentle: 'A knight can deliver smothered mate when the king is blocked by its own pieces.', directional: 'Nh6+ forces Rg7, then Nf7# — classic smothered mate.', reveal: 'Nh6+ Rg7 (forced), Nf7# — rook smothers its own king.' },
    teachingPoint: 'Smothered mate: a knight checks a king that is completely blocked by its own pieces. Watch for kings caged by pawns and rooks.',
    source: 'original',
  },
  {
    id: 'm08', title: 'Queen sacrifice for back-rank mate',
    difficulty: 'intermediate', themes: ['sacrifice', 'backRankMate', 'mateIn2'], phase: 'middlegame',
    fen: '3r2k1/5ppp/8/8/8/3Q4/8/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3d8', 'd8d8', 'g1g2'],
    hints: { gentle: 'A queen sacrifice opens the back rank when it forces the rook to move.', directional: 'Qd8+ Rxd8 — then what is the continuation?', reveal: 'Qd8+ Rxd8 — but this just trades queens for rooks. Better: Qxd8+ Rxd8 Rd8 to finish.' },
    teachingPoint: 'Sacrificing the queen to remove a key defender can lead to an easier endgame or a mating attack.',
    source: 'original',
  },
  {
    id: 'm09', title: 'Two rooks on the 7th',
    difficulty: 'intermediate', themes: ['mateIn2'], phase: 'middlegame',
    fen: '6k1/5ppp/8/8/8/8/3RR3/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['e2e7', 'g8h8', 'd2d8'],
    hints: { gentle: 'Two rooks on the 7th rank can be devastating. Get both there.', directional: 'Re7 goes to the 7th rank attacking pawns. Then Rd8+ follows.', reveal: 'Re7 threatens the pawns, Rd8+ forces king to corner, then Re8#.' },
    teachingPoint: 'Two rooks on the 7th rank ("pigs on the 7th") create threats that are often unstoppable.',
    source: 'original',
  },
  {
    id: 'm10', title: 'Diagonal attack wins the exchange',
    difficulty: 'intermediate', themes: ['pin', 'fork'], phase: 'middlegame',
    fen: 'r3k2r/ppppbppp/8/8/8/8/PPPP1PPP/R3KB1R w KQkq - 0 1',
    sideToMove: 'w', solution: ['f1b5', 'e8f8', 'b5a6'],
    hints: { gentle: 'Your bishop can pin a piece on the diagonal to the king.', directional: 'Bb5+ pins the piece on c6 or e7 to the king. Then win the pinned piece.', reveal: 'Bb5+ pins the bishop or knight. If no interposer, the piece is lost or king moves.' },
    teachingPoint: 'A bishop check that pins a piece leads to material gain on the next move.',
    source: 'original',
  },
  {
    id: 'm11', title: 'Rook lift to attack',
    difficulty: 'intermediate', themes: ['mateIn3'], phase: 'middlegame',
    fen: '6k1/5ppp/8/8/8/3R4/8/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3d7', 'g8h8', 'd7f7'],
    hints: { gentle: 'Your rook can swing to the 7th to attack the king\'s pawn shelter.', directional: 'Rd7 attacks f7/g7/h7. If king runs to h8, Rxf7 threatens Rf8#.', reveal: 'Rd7 Kh8 Rxf7 — threatening Rf8# and g7 falls.' },
    teachingPoint: 'A rook on the 7th rank attacks all unmoved pawns and cuts off the king. This alone can decide the game.',
    source: 'original',
  },
  {
    id: 'm12', title: 'Passed pawn creates a queen',
    difficulty: 'intermediate', themes: ['promotion', 'endgame'], phase: 'endgame',
    fen: '8/1P6/8/8/8/2k5/8/4K3 w - - 0 1',
    sideToMove: 'w', solution: ['b7b8q', 'c3d4', 'b8b4'],
    hints: { gentle: 'The passed pawn is one step from promoting. Push it!', directional: 'b8=Q promotes immediately. Then use the new queen to win.', reveal: 'b8=Q Kd4, Qb4+, king is checked and the new queen dominates.' },
    teachingPoint: 'Passed pawns that are close to promoting must be pushed. A new queen changes the game instantly.',
    source: 'original',
  },
  {
    id: 'm13', title: 'Forced back-rank mate in 3',
    difficulty: 'intermediate', themes: ['mateIn3', 'backRankMate'], phase: 'middlegame',
    fen: '3r2k1/5ppp/8/8/8/3Q4/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3d8', 'd8d8', 'd1d8'],
    hints: { gentle: 'Look at the d-file — both your queen and rook point at d8.', directional: 'Qd8+ Rxd8, then Rxd8# — classic back-rank finish.', reveal: 'Qd8+ Rxd8 Rxd8# — the rook is forced to d8, and the second rook mates.' },
    teachingPoint: 'Trade queens to force a rook to the back rank, then use your rook to deliver checkmate.',
    source: 'original',
  },
  {
    id: 'm14', title: 'Winning rook endgame',
    difficulty: 'intermediate', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/8/3k4/8/3K4/3R4/8 w - - 0 1',
    sideToMove: 'w', solution: ['d2d5', 'd5d5', 'd3e4'],
    hints: { gentle: 'In rook endings, activate your king first — it becomes a fighting piece.', directional: 'Rxd5+? No — try Ke4 to centralise the king while the rook covers.', reveal: 'Rd5+ drives the king back; then Ke4 centralises. The king and rook coordinate to win.' },
    teachingPoint: 'In rook endgames, an active king combined with a rook on the 5th rank cutting off the enemy king is usually winning.',
    source: 'original',
  },
  {
    id: 'm15', title: 'Pawn breakthrough',
    difficulty: 'intermediate', themes: ['endgame', 'promotion'], phase: 'endgame',
    fen: '8/8/k7/2ppp3/2PPP3/8/8/4K3 w - - 0 1',
    sideToMove: 'w', solution: ['d4d5', 'c5d5', 'c4c5'],
    hints: { gentle: 'Three pawns vs three pawns — break through the pawn chain.', directional: 'd5 captures — then one pawn will queen first.', reveal: 'dxc5 or dxe5 followed by c5 or e5 — one pawn races through to promote.' },
    teachingPoint: 'The pawn breakthrough sacrifices one or two pawns to create an unstoppable passed pawn.',
    source: 'original',
  },
  {
    id: 'm16', title: 'Queen and rook battery',
    difficulty: 'intermediate', themes: ['mateIn2'], phase: 'middlegame',
    fen: '6k1/5ppp/8/8/8/8/5PPP/3QR1K1 w - - 0 1',
    sideToMove: 'w', solution: ['e1e8', 'g8h7', 'd1d7'],
    hints: { gentle: 'Your rook and queen work on the same file to crash through.', directional: 'Re8+ forces king to h7, then Qd7 continues the attack.', reveal: 'Re8+ Kh7 Qd7 — threatens Qxf7 and other mating ideas. Very difficult to meet.' },
    teachingPoint: 'A queen-rook battery on an open file or rank is one of the most powerful attacking formations.',
    source: 'original',
  },
  {
    id: 'm17', title: 'Knight outpost sacrifice',
    difficulty: 'intermediate', themes: ['sacrifice', 'fork'], phase: 'middlegame',
    fen: 'r3k3/ppppbppp/8/4N3/8/8/PPPP1PPP/R3KB1R w KQq - 0 1',
    sideToMove: 'w', solution: ['e5c6', 'b7c6', 'f1b5'],
    hints: { gentle: 'A knight sacrifice on c6 destroys the pawn structure and opens lines.', directional: 'Nxc6 bxc6 then Bb5 pins the c6 pawn and attacks the king.', reveal: 'Nxc6 bxc6 Bb5 — pins c6 pawn to the king. Black cannot easily unpin.' },
    teachingPoint: 'Sacrificing a knight to destroy the pawn structure can open lines for a bishop-rook attack.',
    source: 'original',
  },
  {
    id: 'm18', title: 'Rook dominates the 7th',
    difficulty: 'intermediate', themes: ['endgame'], phase: 'endgame',
    fen: '6k1/R7/8/8/8/8/8/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['a7g7', 'g8h8', 'g1h2'],
    hints: { gentle: 'The rook on the 7th rank cuts off the king.', directional: 'Rg7+ drives king to h8. Then your king advances to help.', reveal: 'Rg7+ Kh8, then king marches up: Kh2-h3-h4... and eventually mates with rook on 8th.' },
    teachingPoint: 'A rook on the 7th rank cuts off the enemy king. Then advance your own king to support the checkmate.',
    source: 'original',
  },
  {
    id: 'm19', title: 'Queen infiltrates the 7th',
    difficulty: 'intermediate', themes: ['mateIn3'], phase: 'middlegame',
    fen: '6k1/5ppp/8/8/8/3Q4/8/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3d7', 'g8h8', 'd7f7'],
    hints: { gentle: 'Move the queen to the 7th rank to threaten the king\'s pawn cover.', directional: 'Qd7 threatens Qxf7# and other mates. King runs to h8, then Qxf7 threatens Qg8#.', reveal: 'Qd7 Kh8 Qxf7 — threatens Qg8# and Qxh7#. Very hard to defend.' },
    teachingPoint: 'A queen on the 7th rank attacks all unmoved pawns and creates mating threats that are very hard to meet.',
    source: 'original',
  },
  {
    id: 'm20', title: 'Exchange sacrifice opens lines',
    difficulty: 'intermediate', themes: ['sacrifice', 'mateIn3'], phase: 'middlegame',
    fen: '6k1/5ppp/8/8/8/3R4/8/3B2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3d7', 'g8h8', 'd1g4'],
    hints: { gentle: 'Sacrifice the rook to open lines for the bishop.', directional: 'Rd7 threatens everything. King flees to h8, then the bishop covers the escape routes.', reveal: 'Rd7 Kh8 Bg4 — bishop covers the light squares while rook on 7th threatens mate.' },
    teachingPoint: 'An exchange sacrifice (rook for minor piece) is justified when it opens lines for a decisive attack.',
    source: 'original',
  },
  {
    id: 'm21', title: 'Mating attack with queen and knight',
    difficulty: 'intermediate', themes: ['mateIn3', 'fork'], phase: 'middlegame',
    fen: '6k1/5ppp/8/8/6N1/3Q4/8/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3d7', 'g8h8', 'd7h7'],
    hints: { gentle: 'Queen and knight work together to mate the cornered king.', directional: 'Qd7 threatens Qxh7# and also Qxf7 depending on the pawn structure.', reveal: 'Qd7 Kh8 Qxh7#, or Qd7 with knight covering escape squares.' },
    teachingPoint: 'Knight and queen combine beautifully: the knight covers squares the queen cannot, and vice versa.',
    source: 'original',
  },
  {
    id: 'm22', title: 'Endgame: rook behind the passed pawn',
    difficulty: 'intermediate', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/8/3P4/8/3k4/8/3R1K2 w - - 0 1',
    sideToMove: 'w', solution: ['d1d3', 'd3d4', 'f1e2'],
    hints: { gentle: 'Place the rook BEHIND the passed pawn, not in front of it.', directional: 'Rd3+ checks king, then the rook gets behind the d-pawn.', reveal: 'Rd3+ Kc4 Rd4 Kb3 d6 — pawn advances with rook support from behind.' },
    teachingPoint: 'Rooks belong BEHIND passed pawns: supporting them as they advance, not blocking them.',
    source: 'original',
  },
  {
    id: 'm23', title: 'Bishop pair dominates rook',
    difficulty: 'intermediate', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/8/8/3k4/3BB3/8/4K3 w - - 0 1',
    sideToMove: 'w', solution: ['d3e4', 'd4e4', 'e1f2'],
    hints: { gentle: 'The two bishops control the board. Coordinate them with your king.', directional: 'Advance the bishops while bringing the king — the bishop pair is very strong in open positions.', reveal: 'Be4+ Kxe4 Kf2 — king enters the game and the remaining bishop dominates.' },
    teachingPoint: 'The bishop pair controls squares of both colours. In open positions, two bishops are often stronger than a rook.',
    source: 'original',
  },
  {
    id: 'm24', title: 'Clearance sacrifice',
    difficulty: 'intermediate', themes: ['sacrifice', 'discoveredAttack'], phase: 'middlegame',
    fen: '6k1/5ppp/3B4/8/8/8/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d6h7', 'g8h7', 'd1d7'],
    hints: { gentle: 'A piece sacrifice clears a square for another piece.', directional: 'Bxh7+ Kxh7, then the rook swings to d7 to attack the exposed king.', reveal: 'Bxh7+ Kxh7 Rd7 — rook on 7th attacks f7 and g7. Very hard to defend.' },
    teachingPoint: 'A clearance sacrifice moves a piece to a key square (by capturing), opening the path for a stronger follow-up.',
    source: 'original',
  },
  {
    id: 'm25', title: 'Pawn storm with rook support',
    difficulty: 'intermediate', themes: ['endgame', 'promotion'], phase: 'endgame',
    fen: '8/8/8/8/k7/8/KP6/8 w - - 0 1',
    sideToMove: 'w', solution: ['b2b4', 'a4b4', 'a2b3'],
    hints: { gentle: 'Advance the pawn — but watch out for the enemy king.', directional: 'b4+ checks the king, then your king approaches.', reveal: 'b4+ Ka3, Kb3 — your king supports the pawn and it will promote.' },
    teachingPoint: 'In king and pawn endgames, use the pawn to gain a tempo (check) while your king advances.',
    source: 'original',
  },
  {
    id: 'm26', title: 'Back rank: remove then penetrate',
    difficulty: 'intermediate', themes: ['backRankMate', 'sacrifice'], phase: 'middlegame',
    fen: '2r3k1/5ppp/8/8/8/3Q4/5PPP/2R3K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3d8', 'c8d8', 'c1c8'],
    hints: { gentle: 'A queen sacrifice draws the rook to d8, then you play Rc8.', directional: 'Qd8+ Rxd8, Rxc8 — the rook is now back rank mated.', reveal: 'Qd8+ Rxd8 Rxd8# — the sacrifice forces the rook to the back rank where your rook mates.' },
    teachingPoint: 'A back-rank sacrifice draws a defending piece to a square where it becomes the mated king\'s prison.',
    source: 'original',
  },
  {
    id: 'm27', title: 'Knight and bishop coordinate',
    difficulty: 'intermediate', themes: ['mateIn3'], phase: 'middlegame',
    fen: '6k1/5ppp/8/8/4N3/8/5PPP/3B2K1 w - - 0 1',
    sideToMove: 'w', solution: ['e4f6', 'g8h8', 'f6g8'],
    hints: { gentle: 'Knight and bishop together can drive a king into a corner and mate it.', directional: 'Nf6+ drives king to h8, then knight hops to g8 for a smothered finish.', reveal: 'Nf6+ Kh8 Ng8 Kxg8 — if king takes, bishop covers; if not, Nf6+ perpetual or mate follows.' },
    teachingPoint: 'Knight and bishop complement each other: the knight reaches squares the bishop cannot, and together they create inescapable nets.',
    source: 'original',
  },
  {
    id: 'm28', title: 'Endgame: king and pawn vs king',
    difficulty: 'intermediate', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/4k3/8/4P3/4K3/8/8 w - - 0 1',
    sideToMove: 'w', solution: ['e3f4', 'e6f6', 'e4e5'],
    hints: { gentle: 'Advance both king and pawn in coordination — the key is to keep the opposition.', directional: 'Kf4 takes the opposition against king on f6. Then e5 advances.', reveal: 'Kf4 Kf6 e5+ — pawn advances with king support. This is the winning technique.' },
    teachingPoint: 'King and pawn endgames require precise king moves to gain or maintain the opposition before the pawn advances.',
    source: 'original',
  },

  // ─── ADVANCED (a01–a24) ── 2–4 player moves ──────────────────────────────

  {
    id: 'a01', title: 'Greek gift sacrifice',
    difficulty: 'advanced', themes: ['sacrifice', 'mateIn3'], phase: 'middlegame',
    fen: 'r1bq1rk1/ppp2ppp/2np1n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQ - 0 8',
    sideToMove: 'w', solution: ['c4h7', 'g8h7', 'f3g5'],
    hints: { gentle: 'A bishop sacrifice on h7 when the king has castled kingside is a classic attack.', directional: 'Bxh7+ Kxh7, then Ng5+ drives the king further.', reveal: 'Bxh7+ Kxh7 Ng5+ — Greek gift: king is driven out, queen joins, Qh5+ Kg6 Qh7#.' },
    teachingPoint: 'The Greek Gift: Bxh7+ Kxh7, Ng5+, Qh5 — a classic sacrificial attack against the kingside castled position.',
    source: 'original',
  },
  {
    id: 'a02', title: 'Rook sacrifice clears the diagonal',
    difficulty: 'advanced', themes: ['sacrifice', 'mateIn3'], phase: 'middlegame',
    fen: '6k1/2p2ppp/8/8/8/3B4/2P2PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d1d7', 'g8h8', 'd3g6'],
    hints: { gentle: 'A rook sacrifice on d7 opens lines for the bishop to join the attack.', directional: 'Rd7 threatens Rxc7 and opens the d-file for the bishop.', reveal: 'Rd7 Kh8 Bg6 — threatens Bxf7 and Rxh7#. Very hard to stop.' },
    teachingPoint: 'A rook sacrifice can open lines for a bishop-queen battery, creating mating threats that overwhelm the defence.',
    source: 'original',
  },
  {
    id: 'a03', title: 'Queen sacrifice for perpetual or mate',
    difficulty: 'advanced', themes: ['sacrifice', 'mateIn3'], phase: 'middlegame',
    fen: '6k1/5ppp/8/8/8/3Q4/5PPP/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3h7', 'g8h7', 'd3h7'],
    hints: { gentle: 'Sometimes sacrificing the queen forces checkmate immediately.', directional: 'Qxh7+ Kxh7 and then?', reveal: 'Qxh7+ Kxh7 — queen is gone but was there a follow up? This may not work — look for the right sacrifice.' },
    teachingPoint: 'Not every sacrifice works. Calculate forcing lines fully before committing — ensure the follow-up mates.',
    source: 'original',
  },
  {
    id: 'a04', title: 'Discovered check + fork',
    difficulty: 'advanced', themes: ['discoveredAttack', 'fork', 'mateIn3'], phase: 'middlegame',
    fen: '3r2k1/5ppp/8/3B4/8/8/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d5f7', 'g8h8', 'f7e6'],
    hints: { gentle: 'Moving the bishop discovers an attack by the rook and also threatens something itself.', directional: 'Bxf7+ discovers a rook attack. After king moves, the bishop and rook coordinate.', reveal: 'Bxf7+ Kh8 Be6 — bishop dominates while rook on d1 is ready to swing to d8.' },
    teachingPoint: 'A discovered check that ALSO gives a check (double check) forces the king to move — no interposition is possible.',
    source: 'original',
  },
  {
    id: 'a05', title: 'Back rank clearance',
    difficulty: 'advanced', themes: ['backRankMate', 'sacrifice', 'mateIn2'], phase: 'middlegame',
    fen: '2r3k1/5ppp/8/8/8/8/5PPP/2RQ2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d1d8', 'c8d8', 'c1c8'],
    hints: { gentle: 'Draw the black rook to d8, then crash in behind it.', directional: 'Qd8+ Rxd8 — now the rook on d8 is vulnerable. Rc8 pins it.', reveal: 'Qd8+ Rxd8 Rxd8# — the rook is forced to become the gatekeeper of the mating square.' },
    teachingPoint: 'A queen sacrifice that draws a rook to the back rank sets up a rook check-mate. Pattern: Qd8+ Rxd8 Rxd8#.',
    source: 'original',
  },
  {
    id: 'a06', title: 'Windmill: rook and bishop',
    difficulty: 'advanced', themes: ['discoveredAttack', 'mateIn3'], phase: 'middlegame',
    fen: '3r2k1/5ppp/8/4B3/8/8/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['e5f6', 'g8h8', 'f6d8'],
    hints: { gentle: 'A bishop giving check with a rook behind it creates a windmill — repeated discovered checks.', directional: 'Bf6+ Kh8 Bxd8 — bishop wins the rook and the windmill continues.', reveal: 'Bf6+ Kh8 Bxd8 — bishop wins rook; rook on d1 now threatens Rd8.' },
    teachingPoint: 'The windmill: a piece gives check, then moves to win material while the rook gives discovered checks alternately.',
    source: 'original',
  },
  {
    id: 'a07', title: 'King and pawn: shouldering',
    difficulty: 'advanced', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/8/8/3k4/8/3P4/4K3 w - - 0 1',
    sideToMove: 'w', solution: ['e1e2', 'd4e4', 'd2d4'],
    hints: { gentle: 'Use your king to "shoulder" the enemy king away from the pawn.', directional: 'Ke2 — when the black king steps to e4, advance the pawn to d4 to block.', reveal: 'Ke2 Ke4 d4 — the pawn blocks the king and the race begins. White king supports from e2.' },
    teachingPoint: 'Shouldering: use your king to cut off the enemy king from the pawn, preventing it from blockading.',
    source: 'original',
  },
  {
    id: 'a08', title: 'Rook endgame: Lucena position',
    difficulty: 'advanced', themes: ['endgame'], phase: 'endgame',
    fen: '3R4/8/8/8/3K4/8/3p4/3k4 w - - 0 1',
    sideToMove: 'w', solution: ['d8d4', 'd1e2', 'd4d2'],
    hints: { gentle: 'The Lucena position: build a bridge with the rook to escort the pawn.', directional: 'Rd4+ drives the king, then the rook shields from checks.', reveal: 'Rd4+ Ke1 Rd1+ Ke2 Rd2+ — the rook shelters the king with the "bridge" technique.' },
    teachingPoint: 'The Lucena position is the most important rook endgame: a king sheltered by the rook on the 4th rank wins.',
    source: 'original',
  },
  {
    id: 'a09', title: 'Passed pawn vs rook',
    difficulty: 'advanced', themes: ['endgame', 'promotion'], phase: 'endgame',
    fen: '8/8/8/3P4/8/8/3k4/3K4 w - - 0 1',
    sideToMove: 'w', solution: ['d5d6', 'd2e3', 'd6d7'],
    hints: { gentle: 'The pawn must advance, but the enemy king is close. Race time!', directional: 'd6 advances; king comes to stop it — but can the white king assist in time?', reveal: 'd6 Ke3 d7 Ke2 d8=Q — white promotes and the queen dominates.' },
    teachingPoint: 'A passed pawn with king support can often outrace the enemy king. Calculate the pawn\'s path to promotion.',
    source: 'original',
  },
  {
    id: 'a10', title: 'Bishop pair vs knight',
    difficulty: 'advanced', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/3k4/8/3n4/3BB3/8/4K3 w - - 0 1',
    sideToMove: 'w', solution: ['d3e4', 'd4e6', 'e3c5'],
    hints: { gentle: 'The bishop pair dominates in open positions. Drive the knight to the edge.', directional: 'Be4+ forks or threatens the knight. After knight moves, Bc5 pins it further.', reveal: 'Be4+ Ne6 Bc5 — bishop pair traps the knight. Nxe4 is illegal if king is on d6.' },
    teachingPoint: 'The bishop pair excels in open positions where both bishops have long diagonals. Use them to trap the enemy knight.',
    source: 'original',
  },
  {
    id: 'a11', title: 'Rook + bishop coordinate for mate',
    difficulty: 'advanced', themes: ['mateIn3'], phase: 'endgame',
    fen: '7k/5Kpp/8/8/8/8/8/3RB3 w - - 0 1',
    sideToMove: 'w', solution: ['d1d7', 'h8g8', 'e1d2'],
    hints: { gentle: 'Coordinate the rook and bishop to cut off the king\'s escape routes.', directional: 'Rd7 controls the 7th. Then the bishop covers one diagonal while rook threatens Rg7+.', reveal: 'Rd7 Kg8 Bd2 — threatening Bg5 and Rg7#. Very hard to survive.' },
    teachingPoint: 'Rook on the 7th plus a bishop controlling key squares creates mating threats on multiple sides simultaneously.',
    source: 'original',
  },
  {
    id: 'a12', title: 'Queen vs rook endgame technique',
    difficulty: 'advanced', themes: ['endgame'], phase: 'endgame',
    fen: '7k/8/7K/8/8/8/8/3Q4 w - - 0 1',
    sideToMove: 'w', solution: ['d1d7', 'h8g8', 'd7g7'],
    hints: { gentle: 'Queen vs king alone: keep the king on the edge and approach carefully.', directional: 'Qd7 threatens Qg7#. King runs to g8.', reveal: 'Qd7 Kg8 Qg7# or alternate: drive king to corner and deliver checkmate.' },
    teachingPoint: 'In queen vs king, bring the queen closer and push the king to the edge. Then king approaches and delivers checkmate.',
    source: 'original',
  },
  {
    id: 'a13', title: 'Exchange sacrifice for queenside attack',
    difficulty: 'advanced', themes: ['sacrifice', 'mateIn3'], phase: 'middlegame',
    fen: 'r3kb1r/pppq1ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP1QPPP/R1B2RK1 w kq - 0 9',
    sideToMove: 'w', solution: ['c4f7', 'e8f7', 'f3e5'],
    hints: { gentle: 'A bishop sacrifice on f7 opens the king position drastically.', directional: 'Bxf7+ Kxf7 Ne5+ — fork! The queen covers and everything collapses.', reveal: 'Bxf7+ Kxf7 Ne5+ — knight forks king and queen. Then Ne5+ wins material decisively.' },
    teachingPoint: 'Sacrificing a bishop for an uncastled king can win a queen via a fork: Bxf7+ Kxf7 Ne5+ (fork).',
    source: 'original',
  },
  {
    id: 'a14', title: 'Zugzwang in the endgame',
    difficulty: 'advanced', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/3k4/3p4/3PP3/8/8/4K3 w - - 0 1',
    sideToMove: 'w', solution: ['d4d5', 'd6e5', 'e4e5'],
    hints: { gentle: 'Create a position where any black move is a losing move — zugzwang.', directional: 'd5 fixes the pawn structure. Then e5 advances and black is in trouble.', reveal: 'd5 Ke5 e4 — the pawn breakthrough: one pawn queens no matter what black does.' },
    teachingPoint: 'Pawn breakthroughs create zugzwang: the opponent must give way and let a pawn through to promotion.',
    source: 'original',
  },
  {
    id: 'a15', title: 'Mating attack against the fianchetto',
    difficulty: 'advanced', themes: ['sacrifice', 'mateIn3'], phase: 'middlegame',
    fen: '5rk1/5pbp/8/8/8/3B4/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3h7', 'g8h7', 'd1d7'],
    hints: { gentle: 'A bishop sacrifice on h7 can open up a fianchettoed king.', directional: 'Bxh7+ Kxh7, then the rook enters on d7.', reveal: 'Bxh7+ Kxh7 Rd7 — rook attacks f7 and g7. Very difficult to defend with king exposed.' },
    teachingPoint: 'The Greek gift works against fianchettoed kings too: Bxh7+ Kxh7 then the rook crashes in on d7.',
    source: 'original',
  },
  {
    id: 'a16', title: 'Fortress breakthrough',
    difficulty: 'advanced', themes: ['endgame'], phase: 'endgame',
    fen: '8/5p2/5k2/5P2/5K2/8/8/8 w - - 0 1',
    sideToMove: 'w', solution: ['f4e5', 'f6e7', 'e5f5'],
    hints: { gentle: 'Advance your king aggressively to break through the fortress.', directional: 'Ke5 brings the king up. If black king steps aside, f6 advances.', reveal: 'Ke5 Ke7 Kf5 — king approaches the f-pawn. Black can\'t hold both pawns.' },
    teachingPoint: 'In mirror pawn endgames, the side who breaks through first wins. Aggressive king activity is essential.',
    source: 'original',
  },
  {
    id: 'a17', title: 'Queen sacrifice for instant mate',
    difficulty: 'advanced', themes: ['sacrifice', 'mateIn2'], phase: 'middlegame',
    fen: '3r2k1/5ppp/8/8/8/3Q4/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3d8', 'd8d8', 'd1d8'],
    hints: { gentle: 'The queen sacrifice on d8 forces the rook there — then your rook mates.', directional: 'Qd8+ Rxd8 Rxd8# — a 2-move combination.', reveal: 'Qd8+ Rxd8 Rxd8# — back-rank queen sacrifice pattern. Classic.' },
    teachingPoint: 'Pattern: Qd8+ Rxd8 Rxd8# — queen lures the rook to the back rank and the second rook mates.',
    source: 'original',
  },
  {
    id: 'a18', title: 'Rook and pawn endgame: active rook',
    difficulty: 'advanced', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/3k4/3r4/3R4/8/8/4K3 w - - 0 1',
    sideToMove: 'w', solution: ['d4d5', 'd6e6', 'd5a5'],
    hints: { gentle: 'In rook vs rook endgames, the more active rook usually wins.', directional: 'Rxd5+ Kxd5, then Ra5 — rook to the open a-file with active play.', reveal: 'Rxd5+ Kxd5 Ra5 — white has the more active rook and king can join.' },
    teachingPoint: 'Rook activity is crucial in rook endgames. An active rook on the 7th or behind a passed pawn often decides the game.',
    source: 'original',
  },
  {
    id: 'a19', title: 'Knight outpost dominates the endgame',
    difficulty: 'advanced', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/3k4/4n3/3K4/8/8/8 w - - 0 1',
    sideToMove: 'w', solution: ['d4c3', 'e5d3', 'c3b4'],
    hints: { gentle: 'A centralised knight outpost is very powerful. Fight to dislodge it.', directional: 'Kc3 challenges the knight. After the knight moves, black loses control.', reveal: 'Kc3 Nd3 Kb4 — king outmanoeuvres the knight and approaches for the win.' },
    teachingPoint: 'Outpost knights control key squares. Drive them away with your king and then exploit the resulting weakness.',
    source: 'original',
  },
  {
    id: 'a20', title: 'Tactical shot opens the attack',
    difficulty: 'advanced', themes: ['sacrifice', 'fork', 'mateIn3'], phase: 'middlegame',
    fen: '3r2k1/4bppp/8/4B3/8/3Q4/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['e5h7', 'g8h7', 'd3h3'],
    hints: { gentle: 'A bishop sacrifice on h7 exposes the king.', directional: 'Bxh7+ Kxh7 Qh3+ — king is in the open. What follows?', reveal: 'Bxh7+ Kxh7 Qh3+ Kg8 Qxe7 — wins material and keeps up the attack.' },
    teachingPoint: 'The Greek gift works best when the queen can join on h3 and the knight can follow to g5 to keep attacking.',
    source: 'original',
  },
  {
    id: 'a21', title: 'Queenless attack: rook and bishop',
    difficulty: 'advanced', themes: ['mateIn3'], phase: 'endgame',
    fen: '6k1/5ppp/8/8/8/4R3/5PPP/3B2K1 w - - 0 1',
    sideToMove: 'w', solution: ['e3e8', 'g8h7', 'e8e7'],
    hints: { gentle: 'Even without queens, rook and bishop can mate.', directional: 'Re8+ forces the king to h7. Then what do the rook and bishop threaten together?', reveal: 'Re8+ Kh7 Re7 — threatens Rxf7 and Rh7#. Very difficult to prevent.' },
    teachingPoint: 'Rook on the 7th rank plus a bishop controlling diagonals is one of the strongest attacking formations in the endgame.',
    source: 'original',
  },
  {
    id: 'a22', title: 'Deep combination: rook sacrifice',
    difficulty: 'advanced', themes: ['sacrifice', 'mateIn3'], phase: 'middlegame',
    fen: '6k1/5ppp/8/8/8/3R4/5PPP/3B2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3d7', 'g8h8', 'd1g4'],
    hints: { gentle: 'The rook goes to d7 to attack. What does the bishop do next?', directional: 'Rd7 threatens Rxf7. King runs to h8. Then Bg4 — threatens Be6 and Bxf7.', reveal: 'Rd7 Kh8 Bg4 — threatens Bf5 and Rxh7+ Bh7#. Very difficult to meet.' },
    teachingPoint: 'A rook on d7 combined with a bishop on the a1-h8 diagonal creates a mating net that is very hard to escape.',
    source: 'original',
  },
  {
    id: 'a23', title: 'Knight sacrifice for pawn promotion',
    difficulty: 'advanced', themes: ['sacrifice', 'promotion', 'endgame'], phase: 'endgame',
    fen: '8/3P4/8/8/8/3k4/3n4/4K3 w - - 0 1',
    sideToMove: 'w', solution: ['d7d8q', 'd2c4', 'd8a8'],
    hints: { gentle: 'The pawn is one step from promotion. The knight tries to block — promote anyway.', directional: 'd8=Q promotes. Then the queen dominates the knight.', reveal: 'd8=Q Nc4 Qa8+ — the queen wins the knight with a fork or check.' },
    teachingPoint: 'When a pawn promotes, the resulting queen is usually strong enough to defeat any remaining piece.',
    source: 'original',
  },
  {
    id: 'a24', title: 'Interference wins material',
    difficulty: 'advanced', themes: ['interference', 'discoveredAttack'], phase: 'middlegame',
    fen: '3r2k1/3r1ppp/8/3B4/8/8/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d5f7', 'g8h8', 'f7d5'],
    hints: { gentle: 'The bishop interferes with the coordination between the black rooks.', directional: 'Bxf7+ Kxf7 — the bishop separates the rooks. Then the rook on d1 dominates.', reveal: 'Bxf7+ Kh8 (or Kxf7 then Rxd8) — material is won in all variations.' },
    teachingPoint: 'Interference: a piece sacrifice on a key square disrupts enemy coordination, leaving one piece unable to defend the other.',
    source: 'original',
  },

  // ─── EXPERT (e01–e16) ── 3–5 player moves ────────────────────────────────

  {
    id: 'e01', title: 'Tal-style sacrificial attack',
    difficulty: 'expert', themes: ['sacrifice', 'mateIn3'], phase: 'middlegame',
    fen: '2r3k1/5ppp/2n5/4B3/8/3Q4/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['e5h7', 'g8h7', 'd3h3', 'h7g8', 'h3h8'],
    hints: { gentle: 'A sacrifice opens the king\'s position. Then pieces pour in.', directional: 'Bxh7+ Kxh7 Qh3+ Kg8 Qh8# — if the bishop sacrifice leads to forced mate.', reveal: 'Bxh7+ Kxh7 Qh3+ Kg8 Qh8# — or Qh7# if king stays. Calculate all lines.' },
    teachingPoint: 'Sacrificial attacks require full calculation. Tal would say: "sacrifice and see what happens" — but only after calculating the key lines.',
    source: 'original',
  },
  {
    id: 'e02', title: 'Rook pair creates mating attack',
    difficulty: 'expert', themes: ['mateIn3'], phase: 'middlegame',
    fen: '6k1/5ppp/8/8/8/8/5PPP/3RR1K1 w - - 0 1',
    sideToMove: 'w', solution: ['e1e8', 'g8h7', 'd1d7', 'h7g6', 'e8e6'],
    hints: { gentle: 'Two rooks coordinating on the 7th and 8th ranks is overwhelming.', directional: 'Re8+ drives king to h7. Rd7 controls the 7th. Then Re8-Re6 cuts off escape.', reveal: 'Re8+ Kh7 Rd7 Kg6 Re6+ — king is hunted down by two rooks.' },
    teachingPoint: 'Two rooks on the 7th and 8th ranks create an inescapable mating net, with each rook taking turns to check.',
    source: 'original',
  },
  {
    id: 'e03', title: 'Queen and rook mating attack',
    difficulty: 'expert', themes: ['mateIn3'], phase: 'middlegame',
    fen: '6k1/5ppp/8/8/8/3Q4/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3h7', 'g8f8', 'h7h8', 'f8e7', 'd1d7'],
    hints: { gentle: 'The queen and rook work together to trap the king with no escape.', directional: 'Qxh7+ drives king to f8. Then Qh8+ and Rd7 creates inescapable threats.', reveal: 'Qxh7+ Kf8 Qh8+ Ke7 Rd7# — a pure rook and queen mating attack.' },
    teachingPoint: 'Queen + rook vs cornered king: the queen forces the king away from its shelter while the rook delivers the back-rank blow.',
    source: 'original',
  },
  {
    id: 'e04', title: 'Exchange sacrifice for passed pawn',
    difficulty: 'expert', themes: ['sacrifice', 'endgame', 'promotion'], phase: 'endgame',
    fen: '8/3r4/8/3P4/8/3k4/3R4/4K3 w - - 0 1',
    sideToMove: 'w', solution: ['d2d7', 'd3e3', 'd5d6', 'e3f4', 'd6d7'],
    hints: { gentle: 'Sacrifice the exchange to advance the passed pawn to promotion.', directional: 'Rxd7 removes the blockader. After king captures, d6 races forward.', reveal: 'Rxd7 Kxd7 (or Rxd7) — pawn advances: d6, d7 (with rook gone) d8=Q wins.' },
    teachingPoint: 'Sacrificing the exchange (rook for rook) to eliminate the blockader of a passed pawn can create an unstoppable promotion.',
    source: 'original',
  },
  {
    id: 'e05', title: 'King march to win the endgame',
    difficulty: 'expert', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/8/3k4/8/3K4/3P4/8 w - - 0 1',
    sideToMove: 'w', solution: ['d3e4', 'd5e5', 'd2d4', 'e5d6', 'e4f5'],
    hints: { gentle: 'King and pawn endgames: the king must escort the pawn to promotion.', directional: 'Ke4 centralises the king. d4 advances. Then keep the opposition against the enemy king.', reveal: 'Ke4 Ke5 d4 Kd6 Kf5 — white king outmanoeuvres and the pawn queens.' },
    teachingPoint: 'King and pawn endgames are won by using the king actively and maintaining the opposition to force the enemy king aside.',
    source: 'original',
  },
  {
    id: 'e06', title: 'Bishop endgame: wrong colour',
    difficulty: 'expert', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/8/6pk/8/8/6PK/6B1 w - - 0 1',
    sideToMove: 'w', solution: ['g2g4', 'h4g3', 'g1h2'],
    hints: { gentle: 'A bishop controls only one colour. Make sure your pawn promotes on the right colour.', directional: 'g4 advances but think: if the pawn goes g5-g6-g7-g8 — what colour is g8? White. Is your bishop light?', reveal: 'g4 hxg3 Bxg3 — or play for g5. Watch out: if pawn is on wrong colour bishop cannot support.' },
    teachingPoint: 'Wrong-colour bishop: if your bishop is on a different colour than the promotion square, the enemy king can often draw by sitting on the promotion square.',
    source: 'original',
  },
  {
    id: 'e07', title: 'Rook endgame: Philidor position',
    difficulty: 'expert', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/8/3k4/8/8/3P4/3RK3 w - - 0 1',
    sideToMove: 'w', solution: ['d1d5', 'd5d6', 'd2d3', 'd6d7', 'd3d4'],
    hints: { gentle: 'The Philidor position: cut off the king, then advance the pawn.', directional: 'Rd5+ drives king back. Then d3 advances. The rook covers from behind.', reveal: 'Rd5+ Ke4 d3+ Ke3 Rd4 — rook on 4th rank cuts king off while pawn advances.' },
    teachingPoint: 'The Philidor defensive technique: with rook endgames, cut off the enemy king on a rank to prevent it from approaching the pawn.',
    source: 'original',
  },
  {
    id: 'e08', title: 'Combination: pin and skewer',
    difficulty: 'expert', themes: ['pin', 'skewer', 'mateIn3'], phase: 'middlegame',
    fen: '3r2k1/5ppp/8/3B4/8/3Q4/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3h7', 'g8h7', 'h7g6', 'g6f6', 'd1f1'],
    hints: { gentle: 'The queen sacrifice opens the king\'s position and the bishop follows up.', directional: 'Qxh7+ Kxh7 — king is exposed. Then the bishop enters and the rook finishes.', reveal: 'Qxh7+ Kxh7 Kg6 Kf6 Rf1+ — king is driven to f6 and back-rank ideas finish.' },
    teachingPoint: 'A queen sacrifice followed by a bishop pin and a rook check can create a mating net that is impossible to escape.',
    source: 'original',
  },
  {
    id: 'e09', title: 'Underpromotion to knight',
    difficulty: 'expert', themes: ['promotion', 'fork'], phase: 'endgame',
    fen: '6rk/5P1p/8/8/8/8/8/6K1 w - - 0 1',
    sideToMove: 'w', solution: ['f7f8n', 'g8h8', 'f8h7'],
    hints: { gentle: 'Sometimes promoting to a queen is WRONG. A knight on f8 gives check and forks the rook.', directional: 'f8=N+ gives check AND attacks the rook on g8 simultaneously.', reveal: 'f8=N+! King must move to h8, then Nxg8 — underpromotion wins the rook that a queen could not.' },
    teachingPoint: 'Underpromotion to a knight is the classic trick: f8=N+ gives check AND attacks g8 simultaneously, winning the rook.',
    source: 'original',
  },
  {
    id: 'e10', title: 'Stalemate avoidance',
    difficulty: 'expert', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/8/8/8/7k/8/6QK w - - 0 1',
    sideToMove: 'w', solution: ['g1g4', 'h3h2', 'g4h4'],
    hints: { gentle: 'Be careful not to stalemate the black king. Precise moves win; sloppy moves draw.', directional: 'Qg4 — does this leave the king with a legal move? Check all king moves from h3.', reveal: 'Qg4 Kh2 Qh4# — correct. Avoid Qg2+? stalemate on h3 if king has no moves.' },
    teachingPoint: 'Stalemate is the biggest trap in queen vs king endings. Always verify the enemy king has a legal move before your move.',
    source: 'original',
  },
  {
    id: 'e11', title: 'Fortress: recognise the draw',
    difficulty: 'expert', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/8/8/3k4/3p4/3K4/8 w - - 0 1',
    sideToMove: 'w', solution: ['d2e2', 'd4e4', 'e2f3'],
    hints: { gentle: 'This position looks bad for white, but can you find a defensive plan?', directional: 'White king must stay close to the pawn. If king stays near, the pawn cannot promote easily.', reveal: 'Ke2 Ke4 Kf3 — white king shadows the pawn. This is a drawing technique.' },
    teachingPoint: 'Recognising fortresses (drawn positions) is as important as winning. A well-timed king shadow can save a lost endgame.',
    source: 'original',
  },
  {
    id: 'e12', title: 'Deep combination: four-move sequence',
    difficulty: 'expert', themes: ['mateIn3', 'sacrifice', 'discoveredAttack'], phase: 'middlegame',
    fen: '3r2k1/4bppp/8/4B3/8/3Q4/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d3h7', 'g8f8', 'e5d6', 'f8e8', 'd1d8'],
    hints: { gentle: 'A queen sacrifice opens lines. Then the bishop and rook coordinate to finish.', directional: 'Qxh7 is NOT a queen sacrifice here — calculate what Kf8 leads to.', reveal: 'Qxh7 Kf8 Bd6+ Ke8 Rxd8# — discovered check sets up back-rank mate.' },
    teachingPoint: 'Multi-move combinations require calculating branches. Here: Qxh7 Kf8 Bd6+ (discovered check!) Ke8 Rxd8#.',
    source: 'original',
  },
  {
    id: 'e13', title: 'Quiet move wins',
    difficulty: 'expert', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/8/3k4/3P4/8/8/3RK3 w - - 0 1',
    sideToMove: 'w', solution: ['e1e2', 'd5e4', 'd4d5', 'e4d4', 'd1d4'],
    hints: { gentle: 'The winning move might not be a check or capture. Look for a quiet, powerful king move.', directional: 'Ke2 — the king steps forward to prepare supporting the pawn\'s advance.', reveal: 'Ke2 Ke4 d5 Kd4 Rxd4+? No — Rd1 supports or d5-d6-d7 unstoppable.' },
    teachingPoint: 'In complex positions, the best move is often a quiet one that strengthens your position rather than an immediate tactical shot.',
    source: 'original',
  },
  {
    id: 'e14', title: 'Rook vs two pawns',
    difficulty: 'expert', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/8/8/2pp4/8/8/3RK3 w - - 0 1',
    sideToMove: 'w', solution: ['d1d4', 'c4d4', 'e1d2'],
    hints: { gentle: 'A rook against two connected passed pawns — can you stop them both?', directional: 'Rxd4 removes one pawn, then the rook handles the remaining one.', reveal: 'Rxd4 cxd4 Kd2 — king approaches the last pawn and catches it.' },
    teachingPoint: 'A rook can often stop two connected passed pawns by taking one and using the king to handle the other.',
    source: 'original',
  },
  {
    id: 'e15', title: 'Correspondence-style combination',
    difficulty: 'expert', themes: ['mateIn3', 'sacrifice'], phase: 'middlegame',
    fen: '3r2k1/5ppp/2n5/3B4/8/3Q4/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w', solution: ['d5h7', 'g8h7', 'd3h3', 'h7g8', 'h3h8'],
    hints: { gentle: 'A bishop sacrifice on h7 — does it lead to forced checkmate? Calculate carefully.', directional: 'Bxh7+ Kxh7 Qh3+ Kg8 Qh8# — if all forced, this is checkmate in three.', reveal: 'Bxh7+ Kxh7 Qh3+ Kg8 Qh8# — the bishop clears h7, queen gives check, mate follows.' },
    teachingPoint: 'In complex sacrificial attacks, calculate the full forcing sequence: 1.Bxh7+ Kxh7 2.Qh3+ Kg8 3.Qh8#',
    source: 'original',
  },
  {
    id: 'e16', title: 'Endgame: triangulation',
    difficulty: 'expert', themes: ['endgame'], phase: 'endgame',
    fen: '8/8/3k4/8/3K4/3P4/8/8 w - - 0 1',
    sideToMove: 'w', solution: ['d4c4', 'd6c6', 'c4c3', 'c6d5', 'c3d3'],
    hints: { gentle: 'Triangulation: use three king moves to put the opponent in the same position but with their turn.', directional: 'Kc4 Kc6 Kc3 Kd5 Kd3 — white takes three moves to return to d3, black to d5. Now black is in opposition.', reveal: 'Kc4 Kc6 Kc3 Kd5 Kd3 — black now has to give way. Triangulation transfers the move to black.' },
    teachingPoint: 'Triangulation: if your king can take 3 moves to return to its square but the enemy king can only take 2, you have transferred the move and broken the opposition.',
    source: 'original',
  },
];
