import type { AdultPuzzle } from './types';

// AUTO-GENERATED by scripts/generate-adult-puzzles.mjs — do not edit by hand.
// Every FEN and solution line is verified with chess.js at generation time.
// solution[] interleaves moves: even index = player, odd index = opponent reply.

export const adultPuzzles: AdultPuzzle[] = [
  {
    "id": "i01",
    "title": "Checkmate in one",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/5Q2/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f5a5"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i02",
    "title": "Checkmate in one",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/7Q/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6a6"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i03",
    "title": "Checkmate in one",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/8/8/4Q3/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e3a7"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i04",
    "title": "Checkmate in one",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "1Q6/8/8/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "b8b2"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i05",
    "title": "Checkmate in one",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/8/6Q1/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "g4a4"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i06",
    "title": "Checkmate in one",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/8/8/8/2K5/k2Q4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2b3"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i07",
    "title": "Checkmate in one",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/Q7/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a6a7"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i08",
    "title": "Checkmate in one",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/8/8/8/2K2Q2/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f2a7"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i09",
    "title": "Checkmate in one",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/2Q5/8/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c7a5"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i10",
    "title": "Checkmate in one",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/8/8/7Q/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h3a3"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i11",
    "title": "Win the queen",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/8/2R2q2/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2f2"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your rook can reach the undefended queen in one move.",
      "reveal": "Capture the queen — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "i12",
    "title": "Win the queen",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/2q5/8/5k2/8/8/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c7"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your rook can reach the undefended queen in one move.",
      "reveal": "Capture the queen — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "i13",
    "title": "Win the queen",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/2q5/8/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c4"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your rook can reach the undefended queen in one move.",
      "reveal": "Capture the queen — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "i14",
    "title": "Win the queen",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/8/2R1q3/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e2"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your rook can reach the undefended queen in one move.",
      "reveal": "Capture the queen — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "i15",
    "title": "Win the rook",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/3r4/2B5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d3"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your bishop can reach the undefended rook in one move.",
      "reveal": "Capture the rook — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "i16",
    "title": "Win the rook",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/1r6/2B5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2b3"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your bishop can reach the undefended rook in one move.",
      "reveal": "Capture the rook — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "i17",
    "title": "Win the rook",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/7B/5k2/8/4r3/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6e3"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your bishop can reach the undefended rook in one move.",
      "reveal": "Capture the rook — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "i18",
    "title": "Win the rook",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/7B/5k2/8/8/3r4/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6d2"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your bishop can reach the undefended rook in one move.",
      "reveal": "Capture the rook — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "i19",
    "title": "Promote the pawn",
    "difficulty": "intro",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "8/P7/8/5k2/8/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7a8q"
    ],
    "hints": {
      "gentle": "Your pawn is one step from the far side of the board.",
      "directional": "Advance the pawn to the last rank and choose a new piece.",
      "reveal": "Promote to a queen, gaining the most powerful piece on the board."
    },
    "teachingPoint": "A pawn that reaches the far rank promotes, almost always to a queen. Passed pawns are a major endgame weapon.",
    "source": "generated"
  },
  {
    "id": "i20",
    "title": "Promote the pawn",
    "difficulty": "intro",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "8/P7/8/8/8/8/2k5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7a8q"
    ],
    "hints": {
      "gentle": "Your pawn is one step from the far side of the board.",
      "directional": "Advance the pawn to the last rank and choose a new piece.",
      "reveal": "Promote to a queen, gaining the most powerful piece on the board."
    },
    "teachingPoint": "A pawn that reaches the far rank promotes, almost always to a queen. Passed pawns are a major endgame weapon.",
    "source": "generated"
  },
  {
    "id": "i21",
    "title": "Promote the pawn",
    "difficulty": "intro",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "8/P7/7k/8/8/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7a8q"
    ],
    "hints": {
      "gentle": "Your pawn is one step from the far side of the board.",
      "directional": "Advance the pawn to the last rank and choose a new piece.",
      "reveal": "Promote to a queen, gaining the most powerful piece on the board."
    },
    "teachingPoint": "A pawn that reaches the far rank promotes, almost always to a queen. Passed pawns are a major endgame weapon.",
    "source": "generated"
  },
  {
    "id": "i22",
    "title": "Promote the pawn",
    "difficulty": "intro",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "8/P7/8/8/8/4k3/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7a8q"
    ],
    "hints": {
      "gentle": "Your pawn is one step from the far side of the board.",
      "directional": "Advance the pawn to the last rank and choose a new piece.",
      "reveal": "Promote to a queen, gaining the most powerful piece on the board."
    },
    "teachingPoint": "A pawn that reaches the far rank promotes, almost always to a queen. Passed pawns are a major endgame weapon.",
    "source": "generated"
  },
  {
    "id": "i23",
    "title": "Promote the pawn",
    "difficulty": "intro",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "1k6/P7/8/8/8/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7a8q"
    ],
    "hints": {
      "gentle": "Your pawn is one step from the far side of the board.",
      "directional": "Advance the pawn to the last rank and choose a new piece.",
      "reveal": "Promote to a queen, gaining the most powerful piece on the board."
    },
    "teachingPoint": "A pawn that reaches the far rank promotes, almost always to a queen. Passed pawns are a major endgame weapon.",
    "source": "generated"
  },
  {
    "id": "i24",
    "title": "Promote the pawn",
    "difficulty": "intro",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "8/P7/8/8/6k1/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7a8q"
    ],
    "hints": {
      "gentle": "Your pawn is one step from the far side of the board.",
      "directional": "Advance the pawn to the last rank and choose a new piece.",
      "reveal": "Promote to a queen, gaining the most powerful piece on the board."
    },
    "teachingPoint": "A pawn that reaches the far rank promotes, almost always to a queen. Passed pawns are a major endgame weapon.",
    "source": "generated"
  },
  {
    "id": "b01",
    "title": "Checkmate in one",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/5R2/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f5a5"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your rook to deliver a check that covers every escape square.",
      "reveal": "Play the rook move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b02",
    "title": "Checkmate in one",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/7R/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6a6"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your rook to deliver a check that covers every escape square.",
      "reveal": "Play the rook move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b03",
    "title": "Checkmate in one",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/8/8/4R3/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e3a3"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your rook to deliver a check that covers every escape square.",
      "reveal": "Play the rook move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b04",
    "title": "Checkmate in one",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "1R6/8/8/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "b8a8"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your rook to deliver a check that covers every escape square.",
      "reveal": "Play the rook move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b05",
    "title": "Checkmate in one",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/8/6R1/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "g4a4"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your rook to deliver a check that covers every escape square.",
      "reveal": "Play the rook move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b06",
    "title": "Checkmate in one",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/8/8/8/2K5/k2R4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2b3"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your rook to deliver a check that covers every escape square.",
      "reveal": "Play the rook move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b07",
    "title": "Checkmate in one",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/R7/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a6a7"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your rook to deliver a check that covers every escape square.",
      "reveal": "Play the rook move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b08",
    "title": "Checkmate in one",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/2R5/8/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c7a7"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your rook to deliver a check that covers every escape square.",
      "reveal": "Play the rook move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b09",
    "title": "Checkmate in one",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/8/8/7R/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h3a3"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your rook to deliver a check that covers every escape square.",
      "reveal": "Play the rook move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b10",
    "title": "Checkmate in one",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "4R3/8/8/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e8a8"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your rook to deliver a check that covers every escape square.",
      "reveal": "Play the rook move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b11",
    "title": "Win the bishop",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/8/2R2b2/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2f2"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your rook can reach the undefended bishop in one move.",
      "reveal": "Capture the bishop — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "b12",
    "title": "Win the bishop",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/2b5/8/5k2/8/8/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c7"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your rook can reach the undefended bishop in one move.",
      "reveal": "Capture the bishop — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "b13",
    "title": "Win the bishop",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/2b5/8/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c4"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your rook can reach the undefended bishop in one move.",
      "reveal": "Capture the bishop — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "b14",
    "title": "Win the bishop",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/8/2R5/K1b5 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c1"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your rook can reach the undefended bishop in one move.",
      "reveal": "Capture the bishop — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "b15",
    "title": "Win the bishop",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/8/2R1b3/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e2"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your rook can reach the undefended bishop in one move.",
      "reveal": "Capture the bishop — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "b16",
    "title": "Win the knight",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/8/2B5/K2n4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d1"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your bishop can reach the undefended knight in one move.",
      "reveal": "Capture the knight — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "b17",
    "title": "Win the knight",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/3n4/2B5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d3"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your bishop can reach the undefended knight in one move.",
      "reveal": "Capture the knight — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "b18",
    "title": "Win the knight",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/8/2B5/Kn6 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2b1"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your bishop can reach the undefended knight in one move.",
      "reveal": "Capture the knight — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "b19",
    "title": "Win the knight",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/n7/8/2B5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2a4"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your bishop can reach the undefended knight in one move.",
      "reveal": "Capture the knight — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "b20",
    "title": "Win the knight",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/7B/5k2/8/4n3/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6e3"
    ],
    "hints": {
      "gentle": "One of the enemy pieces has no defender. Free material is the first thing to look for.",
      "directional": "Your bishop can reach the undefended knight in one move.",
      "reveal": "Capture the knight — it is hanging, so this wins material for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest way to gain an advantage.",
    "source": "generated"
  },
  {
    "id": "b21",
    "title": "Knight fork wins the rook",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/6r1/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3g4"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the rook.",
      "reveal": "Jump the knight to fork the king and the rook. After the king moves, capture the rook."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "b22",
    "title": "Knight fork wins the rook",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/1r3k2/8/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4b5"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the rook.",
      "reveal": "Jump the knight to fork the king and the rook. After the king moves, capture the rook."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "b23",
    "title": "Knight fork wins the rook",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/2r5/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3c4"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the rook.",
      "reveal": "Jump the knight to fork the king and the rook. After the king moves, capture the rook."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "b24",
    "title": "Knight fork wins the rook",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/8/2N1r3/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4e2"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the rook.",
      "reveal": "Jump the knight to fork the king and the rook. After the king moves, capture the rook."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "b25",
    "title": "Knight fork wins the rook",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/2r5/5k2/8/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4c6"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the rook.",
      "reveal": "Jump the knight to fork the king and the rook. After the king moves, capture the rook."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "b26",
    "title": "Knight fork wins the rook",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/3r1k2/8/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3d5"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the rook.",
      "reveal": "Jump the knight to fork the king and the rook. After the king moves, capture the rook."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "b27",
    "title": "Knight fork wins the rook",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/5r2/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4f3"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the rook.",
      "reveal": "Jump the knight to fork the king and the rook. After the king moves, capture the rook."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "b28",
    "title": "Knight fork wins the rook",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/8/2N3r1/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3g2"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the rook.",
      "reveal": "Jump the knight to fork the king and the rook. After the king moves, capture the rook."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "m01",
    "title": "Knight fork wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/6q1/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3g4"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the queen.",
      "reveal": "Jump the knight to fork the king and the queen. After the king moves, capture the queen."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "m02",
    "title": "Knight fork wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/1q3k2/8/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4b5"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the queen.",
      "reveal": "Jump the knight to fork the king and the queen. After the king moves, capture the queen."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "m03",
    "title": "Knight fork wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/2q5/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3c4"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the queen.",
      "reveal": "Jump the knight to fork the king and the queen. After the king moves, capture the queen."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "m04",
    "title": "Knight fork wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/8/2N1q3/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4e2"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the queen.",
      "reveal": "Jump the knight to fork the king and the queen. After the king moves, capture the queen."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "m05",
    "title": "Knight fork wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/2q5/5k2/8/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4c6"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the queen.",
      "reveal": "Jump the knight to fork the king and the queen. After the king moves, capture the queen."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "m06",
    "title": "Knight fork wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/3q1k2/8/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3d5"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the queen.",
      "reveal": "Jump the knight to fork the king and the queen. After the king moves, capture the queen."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "m07",
    "title": "Knight fork wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/5q2/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4f3"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the queen.",
      "reveal": "Jump the knight to fork the king and the queen. After the king moves, capture the queen."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "m08",
    "title": "Knight fork wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/8/8/2N3q1/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3g2"
    ],
    "hints": {
      "gentle": "A knight can attack two pieces at once with a single L-shaped jump.",
      "directional": "Find the knight move that gives check and also attacks the queen.",
      "reveal": "Jump the knight to fork the king and the queen. After the king moves, capture the queen."
    },
    "teachingPoint": "A knight fork with check is decisive: the king must answer the check first, leaving the second target to be captured.",
    "source": "generated"
  },
  {
    "id": "m09",
    "title": "Skewer wins the rook",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/1r3k2/8/8/2B5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d3",
      "f5e6",
      "d3b5"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your bishop so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the rook behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m10",
    "title": "Skewer wins the rook",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/6r1/5k2/8/8/2B5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d3",
      "f5e6",
      "d3g6"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your bishop so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the rook behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m11",
    "title": "Skewer wins the rook",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/7r/8/5k2/8/8/2B5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d3",
      "f5e6",
      "d3h7"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your bishop so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the rook behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m12",
    "title": "Skewer wins the rook",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "2r5/8/8/5k2/6B1/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "g4h3",
      "f5f6",
      "h3c8"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your bishop so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the rook behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m13",
    "title": "Skewer wins the rook",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/3r4/8/5k2/6B1/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "g4h3",
      "f5f6",
      "h3d7"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your bishop so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the rook behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m14",
    "title": "Skewer wins the rook",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/4r3/5k2/6B1/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "g4h3",
      "f5f6",
      "h3e6"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your bishop so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the rook behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m15",
    "title": "Skewer wins the rook",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/6r1/5k2/8/8/8/K2B4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "d1c2",
      "f5e6",
      "c2g6"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your bishop so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the rook behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m16",
    "title": "Skewer wins the rook",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/7r/8/5k2/8/8/8/K2B4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "d1c2",
      "f5e6",
      "c2h7"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your bishop so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the rook behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m17",
    "title": "Skewer wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/5q2/8/5k2/8/8/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2f2",
      "f5e6",
      "f2f7"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m18",
    "title": "Skewer wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k1q/8/8/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c5",
      "f5e6",
      "c5h5"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m19",
    "title": "Skewer wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5kq1/8/8/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c5",
      "f5e6",
      "c5g5"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m20",
    "title": "Skewer wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "5q2/8/8/5k2/8/8/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2f2",
      "f5e6",
      "f2f8"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m21",
    "title": "Skewer wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/7R/1q3k2/8/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h5",
      "f5e6",
      "h5b5"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m22",
    "title": "Skewer wins the queen",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/7R/3q1k2/8/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h5",
      "f5e6",
      "h5d5"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a01",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/7R/5R2/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a02",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5R2/8/4R3/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e3e1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a03",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "1R6/8/8/5R2/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "b8b1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a04",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5R2/6R1/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f5f1",
      "a1a2",
      "g4a4"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a05",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5R2/8/8/2K5/k2R4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f5f6",
      "a1a2",
      "f6a6"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a06",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/R7/5R2/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a6a2",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a07",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5R2/8/8/2K2R2/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f2f1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a08",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/2R5/8/5R2/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f5f1",
      "a1a2",
      "c7a7"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a09",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5R2/8/7R/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h3h1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a10",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "4R3/8/8/5R2/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e8e1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a11",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/1R3R2/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "b5b1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a12",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5R2/8/8/2K5/k5R1 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f5f6",
      "a1a2",
      "f6a6"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a13",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/3R4/5R2/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "d6d1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a14",
    "title": "Forced mate in two",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5R2/8/R7/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a3a2",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "a15",
    "title": "Skewer wins the queen",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/7R/2q2k2/8/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h5",
      "f5e6",
      "h5c5"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a16",
    "title": "Skewer wins the queen",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/5q2/8/5k2/8/4R3/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e3f3",
      "f5e6",
      "f3f7"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a17",
    "title": "Skewer wins the queen",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "5q2/8/8/5k2/8/4R3/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e3f3",
      "f5e6",
      "f3f8"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a18",
    "title": "Skewer wins the queen",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "1R6/8/8/5k2/8/8/5q2/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "b8f8",
      "f5e6",
      "f8f2"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a19",
    "title": "Skewer wins the queen",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/6q1/5k2/8/8/2B5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d3",
      "f5e6",
      "d3g6"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a20",
    "title": "Skewer wins the queen",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/7q/8/5k2/8/8/2B5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d3",
      "f5e6",
      "d3h7"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a21",
    "title": "Skewer wins the queen",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "2q5/8/8/5k2/6B1/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "g4h3",
      "f5f6",
      "h3c8"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a22",
    "title": "Skewer wins the queen",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/3q4/8/5k2/6B1/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "g4h3",
      "f5f6",
      "h3d7"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a23",
    "title": "Skewer wins the queen",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/4q3/5k2/6B1/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "g4h3",
      "f5f6",
      "h3e6"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a24",
    "title": "Skewer wins the queen",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/6q1/5k2/8/8/8/K2B4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "d1c2",
      "f5e6",
      "c2g6"
    ],
    "hints": {
      "gentle": "Line up your piece so it checks the king with another piece behind it.",
      "directional": "Give check with your rook so the king must step aside.",
      "reveal": "Check the king; when it moves off the line, capture the queen behind it."
    },
    "teachingPoint": "A skewer attacks a valuable piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "e01",
    "title": "Forced mate in two",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5K2/8/4R3/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c1",
      "a1a2",
      "e3a3"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "e02",
    "title": "Forced mate in two",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "1R6/8/8/5K2/8/8/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c3",
      "a1a2",
      "c3a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "e03",
    "title": "Forced mate in two",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5K2/8/8/2Q5/k2R4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c3",
      "a1a2",
      "d1a1"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "e04",
    "title": "Forced mate in two",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/R7/5K2/8/8/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c3",
      "a1b1",
      "a6a1"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "e05",
    "title": "Forced mate in two",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5K2/8/8/2Q2R2/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2a4",
      "a1b1",
      "a4d1"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "e06",
    "title": "Forced mate in two",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5K2/8/7R/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c1",
      "a1a2",
      "h3a3"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "e07",
    "title": "Forced mate in two",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/1R3K2/8/8/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c3",
      "a1a2",
      "c3a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "e08",
    "title": "Forced mate in two",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5K2/8/8/2Q5/k5R1 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c3",
      "a1a2",
      "g1a1"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "e09",
    "title": "Forced mate in two",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5K2/8/R7/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c3",
      "a1b1",
      "a3a1"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "e10",
    "title": "Forced mate in two",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5K2/8/3R4/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c1",
      "a1a2",
      "d3a3"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "e11",
    "title": "Forced mate in two",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "R7/8/8/5K2/8/8/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c3",
      "a1b1",
      "a8a1"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "e12",
    "title": "Forced mate in two",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5K2/8/8/2Q5/k1R5 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c3",
      "a1a2",
      "c1a1"
    ],
    "hints": {
      "gentle": "You can force checkmate in two moves. Start with a check that gives the king only one reply.",
      "directional": "Find the check that leaves exactly one legal answer, then deliver mate.",
      "reveal": "Give the forcing check; after the only legal reply, the second move is checkmate."
    },
    "teachingPoint": "Forcing checks limit the opponent's options. When a check leaves only one reply, you can calculate the mate to the end.",
    "source": "generated"
  },
  {
    "id": "e13",
    "title": "Checkmate in one",
    "difficulty": "expert",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "4Q3/8/8/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e8a4"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "e14",
    "title": "Checkmate in one",
    "difficulty": "expert",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/1Q6/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "b5a6"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "e15",
    "title": "Checkmate in one",
    "difficulty": "expert",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/8/8/8/2K5/k5Q1 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2b3"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "e16",
    "title": "Checkmate in one",
    "difficulty": "expert",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/3Q4/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "d6a3"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move. Look for a check the king cannot escape.",
      "directional": "Use your queen to deliver a check that covers every escape square.",
      "reveal": "Play the queen move that gives check with no legal reply — that is checkmate."
    },
    "teachingPoint": "Checkmate ends the game. Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  }
];
