import type { AdultPuzzle } from './types';

// AUTO-GENERATED by scripts/generate-adult-puzzles.mjs — do not edit by hand.
// Every FEN, solution line, and tactic is verified with chess.js at generation time.
// solution[] interleaves moves: even index = player, odd index = opponent reply.

export const adultPuzzles: AdultPuzzle[] = [
  {
    "id": "i01",
    "title": "Mate in one: Qa5#",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/5Q2/5p2/8/2K4p/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f5a5"
    ],
    "hints": {
      "gentle": "One move ends it. Find the check that the king cannot escape.",
      "directional": "Bring the queen to a5; it covers every escape square.",
      "reveal": "Play Qa5# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i02",
    "title": "Mate in one: Qa6#",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/2p5/7Q/8/1p6/2p5/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6a6"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move — look for a check the king cannot answer.",
      "directional": "Bring the queen to a6; it covers every escape square.",
      "reveal": "Play Qa6# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i03",
    "title": "Mate in one: Qa7#",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/4p3/8/8/4Q3/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e3a7"
    ],
    "hints": {
      "gentle": "One move ends it. Find the check that the king cannot escape.",
      "directional": "Bring the queen to a7; it covers every escape square.",
      "reveal": "Play Qa7# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i04",
    "title": "Mate in one: Qb2#",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "1Q6/8/P1p5/8/3p4/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "b8b2"
    ],
    "hints": {
      "gentle": "Mate is available right now. Which check leaves the king no square, no block, no capture?",
      "directional": "Bring the queen to b2; it covers every escape square.",
      "reveal": "Play Qb2# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i05",
    "title": "Mate in one: Qa4#",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/p7/8/6Q1/8/2K2p1p/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "g4a4"
    ],
    "hints": {
      "gentle": "Mate is available right now. Which check leaves the king no square, no block, no capture?",
      "directional": "Bring the queen to a4; it covers every escape square.",
      "reveal": "Play Qa4# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i06",
    "title": "Mate in one: Qxa7#",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/p7/8/8/8/3P4/2K2Q1p/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f2a7"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move — look for a check the king cannot answer.",
      "directional": "Bring the queen to a7; it covers every escape square.",
      "reveal": "Play Qxa7# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i07",
    "title": "Mate in one: Qa5#",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/2Q5/4p3/2p5/8/6P1/1pK5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c7a5"
    ],
    "hints": {
      "gentle": "One move ends it. Find the check that the king cannot escape.",
      "directional": "Bring the queen to a5; it covers every escape square.",
      "reveal": "Play Qa5# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i08",
    "title": "Mate in one: Qa3#",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/5p2/8/6p1/7Q/2K3p1/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h3a3"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move — look for a check the king cannot answer.",
      "directional": "Bring the queen to a3; it covers every escape square.",
      "reveal": "Play Qa3# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i09",
    "title": "Win the loose queen on f2 (Rxf2+)",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/5p2/5k2/8/7p/2R2q2/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2f2"
    ],
    "hints": {
      "gentle": "An enemy piece is sitting undefended. Free material is the first thing to grab.",
      "directional": "Your rook can take the queen on f2 — it has no defender.",
      "reveal": "Play Rxf2+, winning the queen for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "i10",
    "title": "Win the loose queen on c7 (Rxc7)",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/2qP4/8/5k2/8/8/p1R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c7"
    ],
    "hints": {
      "gentle": "An enemy piece is sitting undefended. Free material is the first thing to grab.",
      "directional": "Your rook can take the queen on c7 — it has no defender.",
      "reveal": "Play Rxc7, winning the queen for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "i11",
    "title": "Win the loose queen on c4 (Rxc4)",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/2q5/3P1p2/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c4"
    ],
    "hints": {
      "gentle": "Something is hanging. Look for the capture that costs you nothing.",
      "directional": "Your rook can take the queen on c4 — it has no defender.",
      "reveal": "Play Rxc4, winning the queen for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "i12",
    "title": "Win the loose rook on d3 (Bxd3+)",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/1P5p/5kp1/8/3r4/2B1p3/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d3"
    ],
    "hints": {
      "gentle": "Scan for pieces with no defender — one of them can simply be taken.",
      "directional": "Your bishop can take the rook on d3 — it has no defender.",
      "reveal": "Play Bxd3+, winning the rook for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "i13",
    "title": "Win the loose rook on e3 (Bxe3)",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/6PB/5k2/8/4r2p/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6e3"
    ],
    "hints": {
      "gentle": "Scan for pieces with no defender — one of them can simply be taken.",
      "directional": "Your bishop can take the rook on e3 — it has no defender.",
      "reveal": "Play Bxe3, winning the rook for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "i14",
    "title": "Win the loose rook on d2 (Bxd2)",
    "difficulty": "intro",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/5p2/5p1B/5k2/2P5/3p4/3r4/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6d2"
    ],
    "hints": {
      "gentle": "Scan for pieces with no defender — one of them can simply be taken.",
      "directional": "Your bishop can take the rook on d2 — it has no defender.",
      "reveal": "Play Bxd2, winning the rook for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "i15",
    "title": "Promote the pawn: a8=Q",
    "difficulty": "intro",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "8/Pp6/6p1/5k2/8/5P2/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7a8q"
    ],
    "hints": {
      "gentle": "Your pawn is one step from the far rank. Turn it into your strongest piece.",
      "directional": "Advance to a8 and promote: a8=Q.",
      "reveal": "Play a8=Q, gaining a queen."
    },
    "teachingPoint": "A pawn reaching the far rank promotes, almost always to a queen — a decisive endgame weapon.",
    "source": "generated"
  },
  {
    "id": "i16",
    "title": "Promote the pawn: a8=Q",
    "difficulty": "intro",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "8/P1p5/8/8/8/8/2k5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7a8q"
    ],
    "hints": {
      "gentle": "A passed pawn is about to promote — push it home.",
      "directional": "Advance to a8 and promote: a8=Q.",
      "reveal": "Play a8=Q, gaining a queen."
    },
    "teachingPoint": "A pawn reaching the far rank promotes, almost always to a queen — a decisive endgame weapon.",
    "source": "generated"
  },
  {
    "id": "i17",
    "title": "Promote the pawn: a8=Q",
    "difficulty": "intro",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "8/P7/7k/8/3p4/2P5/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7a8q"
    ],
    "hints": {
      "gentle": "A passed pawn is about to promote — push it home.",
      "directional": "Advance to a8 and promote: a8=Q.",
      "reveal": "Play a8=Q, gaining a queen."
    },
    "teachingPoint": "A pawn reaching the far rank promotes, almost always to a queen — a decisive endgame weapon.",
    "source": "generated"
  },
  {
    "id": "i18",
    "title": "Promote the pawn: a8=Q",
    "difficulty": "intro",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "8/P7/p7/2P5/5p2/4k3/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7a8q"
    ],
    "hints": {
      "gentle": "A passed pawn is about to promote — push it home.",
      "directional": "Advance to a8 and promote: a8=Q.",
      "reveal": "Play a8=Q, gaining a queen."
    },
    "teachingPoint": "A pawn reaching the far rank promotes, almost always to a queen — a decisive endgame weapon.",
    "source": "generated"
  },
  {
    "id": "i19",
    "title": "Promote the pawn: a8=Q",
    "difficulty": "intro",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "8/P7/8/8/1pP3k1/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7a8q"
    ],
    "hints": {
      "gentle": "A passed pawn is about to promote — push it home.",
      "directional": "Advance to a8 and promote: a8=Q.",
      "reveal": "Play a8=Q, gaining a queen."
    },
    "teachingPoint": "A pawn reaching the far rank promotes, almost always to a queen — a decisive endgame weapon.",
    "source": "generated"
  },
  {
    "id": "i20",
    "title": "Mate in one: Ra5#",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/4p3/8/5R2/1p6/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f5a5"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move — look for a check the king cannot answer.",
      "directional": "Bring the rook to a5; it covers every escape square.",
      "reveal": "Play Ra5# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i21",
    "title": "Mate in one: Rxa6#",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/p6R/8/3p4/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6a6"
    ],
    "hints": {
      "gentle": "One move ends it. Find the check that the king cannot escape.",
      "directional": "Bring the rook to a6; it covers every escape square.",
      "reveal": "Play Rxa6# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i22",
    "title": "Mate in one: Ra3#",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/8/6p1/4R3/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e3a3"
    ],
    "hints": {
      "gentle": "One move ends it. Find the check that the king cannot escape.",
      "directional": "Bring the rook to a3; it covers every escape square.",
      "reveal": "Play Ra3# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "i23",
    "title": "Back-rank mate: Ra8#",
    "difficulty": "intro",
    "themes": [
      "mateIn1",
      "backRankMate"
    ],
    "phase": "endgame",
    "fen": "1R6/6p1/8/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "b8a8"
    ],
    "hints": {
      "gentle": "Mate is available right now. Which check leaves the king no square, no block, no capture?",
      "directional": "Bring the rook to a8; it covers every escape square.",
      "reveal": "Play Ra8# — checkmate."
    },
    "teachingPoint": "Back-rank mates strike a king trapped behind its own pawns. After castling, give your king luft.",
    "source": "generated"
  },
  {
    "id": "i24",
    "title": "Mate in one: Ra4#",
    "difficulty": "intro",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/8/6R1/8/1pK5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "g4a4"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move — look for a check the king cannot answer.",
      "directional": "Bring the rook to a4; it covers every escape square.",
      "reveal": "Play Ra4# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b01",
    "title": "Mate in one: Ra7#",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/2R5/4p3/1P6/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c7a7"
    ],
    "hints": {
      "gentle": "Mate is available right now. Which check leaves the king no square, no block, no capture?",
      "directional": "Bring the rook to a7; it covers every escape square.",
      "reveal": "Play Ra7# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b02",
    "title": "Mate in one: Ra3#",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/5p2/8/8/8/7R/2K3p1/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h3a3"
    ],
    "hints": {
      "gentle": "Mate is available right now. Which check leaves the king no square, no block, no capture?",
      "directional": "Bring the rook to a3; it covers every escape square.",
      "reveal": "Play Ra3# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b03",
    "title": "Back-rank mate: Ra8#",
    "difficulty": "beginner",
    "themes": [
      "mateIn1",
      "backRankMate"
    ],
    "phase": "endgame",
    "fen": "4R3/7p/8/3p4/8/8/1pK5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e8a8"
    ],
    "hints": {
      "gentle": "There is a checkmate in one move — look for a check the king cannot answer.",
      "directional": "Bring the rook to a8; it covers every escape square.",
      "reveal": "Play Ra8# — checkmate."
    },
    "teachingPoint": "Back-rank mates strike a king trapped behind its own pawns. After castling, give your king luft.",
    "source": "generated"
  },
  {
    "id": "b04",
    "title": "Mate in one: Ra5#",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/7p/1R6/3p4/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "b5a5"
    ],
    "hints": {
      "gentle": "One move ends it. Find the check that the king cannot escape.",
      "directional": "Bring the rook to a5; it covers every escape square.",
      "reveal": "Play Ra5# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b05",
    "title": "Mate in one: Ra6#",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/6p1/3R3p/8/8/6p1/2KP4/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "d6a6"
    ],
    "hints": {
      "gentle": "One move ends it. Find the check that the king cannot escape.",
      "directional": "Bring the rook to a6; it covers every escape square.",
      "reveal": "Play Ra6# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b06",
    "title": "Mate in one: Ra7#",
    "difficulty": "beginner",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/5R2/4p3/8/8/5p2/2K1p3/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f7a7"
    ],
    "hints": {
      "gentle": "One move ends it. Find the check that the king cannot escape.",
      "directional": "Bring the rook to a7; it covers every escape square.",
      "reveal": "Play Ra7# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "b07",
    "title": "Win the loose bishop on f2 (Rxf2+)",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/7p/5p2/5k2/8/8/2R2bP1/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2f2"
    ],
    "hints": {
      "gentle": "An enemy piece is sitting undefended. Free material is the first thing to grab.",
      "directional": "Your rook can take the bishop on f2 — it has no defender.",
      "reveal": "Play Rxf2+, winning the bishop for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "b08",
    "title": "Win the loose bishop on c7 (Rxc7)",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/2b5/8/3p1k2/8/3p4/2R1p3/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c7"
    ],
    "hints": {
      "gentle": "Something is hanging. Look for the capture that costs you nothing.",
      "directional": "Your rook can take the bishop on c7 — it has no defender.",
      "reveal": "Play Rxc7, winning the bishop for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "b09",
    "title": "Win the loose bishop on c4 (Rxc4)",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/p1b5/3pp3/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c4"
    ],
    "hints": {
      "gentle": "Scan for pieces with no defender — one of them can simply be taken.",
      "directional": "Your rook can take the bishop on c4 — it has no defender.",
      "reveal": "Play Rxc4, winning the bishop for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "b10",
    "title": "Win the loose bishop on c1 (Rxc1)",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/2P5/4p3/5k2/8/8/2R5/K1b5 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c1"
    ],
    "hints": {
      "gentle": "Scan for pieces with no defender — one of them can simply be taken.",
      "directional": "Your rook can take the bishop on c1 — it has no defender.",
      "reveal": "Play Rxc1, winning the bishop for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "b11",
    "title": "Win the loose bishop on e2 (Rxe2)",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5kP1/p7/8/2R1b3/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e2"
    ],
    "hints": {
      "gentle": "Something is hanging. Look for the capture that costs you nothing.",
      "directional": "Your rook can take the bishop on e2 — it has no defender.",
      "reveal": "Play Rxe2, winning the bishop for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "b12",
    "title": "Win the loose knight on d3 (Bxd3+)",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/4p3/6pP/5k2/8/3n4/2B5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d3"
    ],
    "hints": {
      "gentle": "Scan for pieces with no defender — one of them can simply be taken.",
      "directional": "Your bishop can take the knight on d3 — it has no defender.",
      "reveal": "Play Bxd3+, winning the knight for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "b13",
    "title": "Win the loose knight on e3 (Bxe3)",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/5p2/7B/5k2/8/4n3/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6e3"
    ],
    "hints": {
      "gentle": "An enemy piece is sitting undefended. Free material is the first thing to grab.",
      "directional": "Your bishop can take the knight on e3 — it has no defender.",
      "reveal": "Play Bxe3, winning the knight for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "b14",
    "title": "Win the loose knight on c1 (Bxc1)",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/7B/5k2/8/1p6/8/K1n5 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6c1"
    ],
    "hints": {
      "gentle": "Scan for pieces with no defender — one of them can simply be taken.",
      "directional": "Your bishop can take the knight on c1 — it has no defender.",
      "reveal": "Play Bxc1, winning the knight for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "b15",
    "title": "Win the loose knight on d2 (Bxd2)",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/6p1/2P4B/5k2/3p4/8/3n4/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6d2"
    ],
    "hints": {
      "gentle": "Scan for pieces with no defender — one of them can simply be taken.",
      "directional": "Your bishop can take the knight on d2 — it has no defender.",
      "reveal": "Play Bxd2, winning the knight for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "b16",
    "title": "Win the loose knight on f8 (Bxf8)",
    "difficulty": "beginner",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "5n2/8/7B/5k2/1P4p1/2p5/5p2/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6f8"
    ],
    "hints": {
      "gentle": "Something is hanging. Look for the capture that costs you nothing.",
      "directional": "Your bishop can take the knight on f8 — it has no defender.",
      "reveal": "Play Bxf8, winning the knight for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "b17",
    "title": "Knight fork wins the rook: Ne3+",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/1p4r1/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3g4"
    ],
    "hints": {
      "gentle": "A knight can attack two things at once — find the move that checks and forks.",
      "directional": "Play Ne3+ (check). After the king moves, Nxg4 wins the rook.",
      "reveal": "Play Ne3+ and then Nxg4 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "b18",
    "title": "Knight fork wins the rook: Nd4+",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/2P3p1/1r3k2/8/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4b5"
    ],
    "hints": {
      "gentle": "A knight can attack two things at once — find the move that checks and forks.",
      "directional": "Play Nd4+ (check). After the king moves, Nxb5 wins the rook.",
      "reveal": "Play Nd4+ and then Nxb5 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "b19",
    "title": "Knight fork wins the rook: Ne3+",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/2r5/8/2N3p1/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3c4"
    ],
    "hints": {
      "gentle": "A knight can attack two things at once — find the move that checks and forks.",
      "directional": "Play Ne3+ (check). After the king moves, Nxc4 wins the rook.",
      "reveal": "Play Ne3+ and then Nxc4 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "b20",
    "title": "Knight fork wins the rook: Nd4+",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/p1pP4/5k2/1p6/8/2N1r3/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4e2"
    ],
    "hints": {
      "gentle": "Look for a single move that gives check and also attacks a bigger piece.",
      "directional": "Play Nd4+ (check). After the king moves, Nxe2 wins the rook.",
      "reveal": "Play Nd4+ and then Nxe2 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "b21",
    "title": "Knight fork wins the rook: Nd4+",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/P7/2r3p1/1p3k2/8/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4c6"
    ],
    "hints": {
      "gentle": "Look for a single move that gives check and also attacks a bigger piece.",
      "directional": "Play Nd4+ (check). After the king moves, Nxc6 wins the rook.",
      "reveal": "Play Nd4+ and then Nxc6 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "b22",
    "title": "Knight fork wins the rook: Ne3+",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/3r1k2/pP6/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3d5"
    ],
    "hints": {
      "gentle": "Look for a single move that gives check and also attacks a bigger piece.",
      "directional": "Play Ne3+ (check). After the king moves, Nxd5 wins the rook.",
      "reveal": "Play Ne3+ and then Nxd5 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "b23",
    "title": "Knight fork wins the rook: Nd4+",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/1p5P/5r2/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4f3"
    ],
    "hints": {
      "gentle": "A knight can attack two things at once — find the move that checks and forks.",
      "directional": "Play Nd4+ (check). After the king moves, Nxf3 wins the rook.",
      "reveal": "Play Nd4+ and then Nxf3 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "b24",
    "title": "Knight fork wins the rook: Ne3+",
    "difficulty": "beginner",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/1p6/8/5k2/8/8/2N3r1/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3g2"
    ],
    "hints": {
      "gentle": "A knight can attack two things at once — find the move that checks and forks.",
      "directional": "Play Ne3+ (check). After the king moves, Nxg2 wins the rook.",
      "reveal": "Play Ne3+ and then Nxg2 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "b25",
    "title": "Promote with capture: axb8=Q",
    "difficulty": "beginner",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "1r6/P3p3/8/5k2/8/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7b8q"
    ],
    "hints": {
      "gentle": "A passed pawn is about to promote — push it home.",
      "directional": "Capture into promotion with axb8=Q, making a new queen.",
      "reveal": "Play axb8=Q, gaining a queen."
    },
    "teachingPoint": "A pawn reaching the far rank promotes, almost always to a queen — a decisive endgame weapon.",
    "source": "generated"
  },
  {
    "id": "b26",
    "title": "Promote with capture: axb8=Q",
    "difficulty": "beginner",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "1r6/P7/8/2pp4/3p4/8/2k5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7b8q"
    ],
    "hints": {
      "gentle": "Your pawn is one step from the far rank. Turn it into your strongest piece.",
      "directional": "Capture into promotion with axb8=Q, making a new queen.",
      "reveal": "Play axb8=Q, gaining a queen."
    },
    "teachingPoint": "A pawn reaching the far rank promotes, almost always to a queen — a decisive endgame weapon.",
    "source": "generated"
  },
  {
    "id": "b27",
    "title": "Promote with capture: axb8=Q",
    "difficulty": "beginner",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "1r6/P7/3P3k/8/3p4/p6p/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7b8q"
    ],
    "hints": {
      "gentle": "Your pawn is one step from the far rank. Turn it into your strongest piece.",
      "directional": "Capture into promotion with axb8=Q, making a new queen.",
      "reveal": "Play axb8=Q, gaining a queen."
    },
    "teachingPoint": "A pawn reaching the far rank promotes, almost always to a queen — a decisive endgame weapon.",
    "source": "generated"
  },
  {
    "id": "b28",
    "title": "Promote with capture: axb8=Q",
    "difficulty": "beginner",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "1r6/P7/8/8/8/4k3/5p2/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7b8q"
    ],
    "hints": {
      "gentle": "Your pawn is one step from the far rank. Turn it into your strongest piece.",
      "directional": "Capture into promotion with axb8=Q, making a new queen.",
      "reveal": "Play axb8=Q, gaining a queen."
    },
    "teachingPoint": "A pawn reaching the far rank promotes, almost always to a queen — a decisive endgame weapon.",
    "source": "generated"
  },
  {
    "id": "m01",
    "title": "Knight fork wins the queen: Nxe3+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/6q1/4p3/2N2p2/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3g4"
    ],
    "hints": {
      "gentle": "A knight can attack two things at once — find the move that checks and forks.",
      "directional": "Play Nxe3+ (check). After the king moves, Nxg4 wins the queen.",
      "reveal": "Play Nxe3+ and then Nxg4 — winning the queen."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m02",
    "title": "Knight fork wins the queen: Nd4+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/1q1p1k2/4p3/8/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4b5"
    ],
    "hints": {
      "gentle": "Look for a single move that gives check and also attacks a bigger piece.",
      "directional": "Play Nd4+ (check). After the king moves, Nxb5 wins the queen.",
      "reveal": "Play Nd4+ and then Nxb5 — winning the queen."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m03",
    "title": "Knight fork wins the queen: Ne3+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/5k2/2q5/8/2N2p2/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3c4"
    ],
    "hints": {
      "gentle": "Look for a single move that gives check and also attacks a bigger piece.",
      "directional": "Play Ne3+ (check). After the king moves, Nxc4 wins the queen.",
      "reveal": "Play Ne3+ and then Nxc4 — winning the queen."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m04",
    "title": "Knight fork wins the queen: Nd4+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/6p1/8/5k2/8/2P5/2N1q3/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4e2"
    ],
    "hints": {
      "gentle": "Look for a single move that gives check and also attacks a bigger piece.",
      "directional": "Play Nd4+ (check). After the king moves, Nxe2 wins the queen.",
      "reveal": "Play Nd4+ and then Nxe2 — winning the queen."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m05",
    "title": "Knight fork wins the queen: Nd4+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/2q5/5k2/8/5p2/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4c6"
    ],
    "hints": {
      "gentle": "Look for a single move that gives check and also attacks a bigger piece.",
      "directional": "Play Nd4+ (check). After the king moves, Nxc6 wins the queen.",
      "reveal": "Play Nd4+ and then Nxc6 — winning the queen."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m06",
    "title": "Knight fork wins the queen: Ne3+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/2pq1k2/8/2p4p/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e3",
      "f5e6",
      "e3d5"
    ],
    "hints": {
      "gentle": "A knight can attack two things at once — find the move that checks and forks.",
      "directional": "Play Ne3+ (check). After the king moves, Nxd5 wins the queen.",
      "reveal": "Play Ne3+ and then Nxd5 — winning the queen."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m07",
    "title": "Knight fork wins the queen: Nd4+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/1p6/5k2/2p5/5q2/2N5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2d4",
      "f5f6",
      "d4f3"
    ],
    "hints": {
      "gentle": "A knight can attack two things at once — find the move that checks and forks.",
      "directional": "Play Nd4+ (check). After the king moves, Nxf3 wins the queen.",
      "reveal": "Play Nd4+ and then Nxf3 — winning the queen."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m08",
    "title": "Queen fork wins the rook: Qh7+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/1p6/7Q/5k2/8/4p3/2r5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h7",
      "f5e6",
      "h7c2"
    ],
    "hints": {
      "gentle": "Look for a single move that gives check and also attacks a bigger piece.",
      "directional": "Play Qh7+ (check). After the king moves, Qxc2 wins the rook.",
      "reveal": "Play Qh7+ and then Qxc2 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m09",
    "title": "Queen fork wins the rook: Qf8+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/2p4Q/5k2/8/8/4Pr2/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6f8",
      "f5e6",
      "f8f2"
    ],
    "hints": {
      "gentle": "A queen can attack two things at once — find the move that checks and forks.",
      "directional": "Play Qf8+ (check). After the king moves, Qxf2 wins the rook.",
      "reveal": "Play Qf8+ and then Qxf2 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m10",
    "title": "Queen fork wins the rook: Qh5+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "4r3/2p5/7Q/5k2/8/5p2/1P3p2/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h5",
      "f5e6",
      "h5e8"
    ],
    "hints": {
      "gentle": "A queen can attack two things at once — find the move that checks and forks.",
      "directional": "Play Qh5+ (check). After the king moves, Qxe8+ wins the rook.",
      "reveal": "Play Qh5+ and then Qxe8+ — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m11",
    "title": "Queen fork wins the rook: Qh5+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/7Q/1r3k2/1p6/6p1/2p5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h5",
      "f5e6",
      "h5b5"
    ],
    "hints": {
      "gentle": "A queen can attack two things at once — find the move that checks and forks.",
      "directional": "Play Qh5+ (check). After the king moves, Qxb5 wins the rook.",
      "reveal": "Play Qh5+ and then Qxb5 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m12",
    "title": "Queen fork wins the rook: Qh5+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/5r2/7Q/5k2/8/8/p2p1p2/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h5",
      "f5e6",
      "h5f7"
    ],
    "hints": {
      "gentle": "Look for a single move that gives check and also attacks a bigger piece.",
      "directional": "Play Qh5+ (check). After the king moves, Qxf7+ wins the rook.",
      "reveal": "Play Qh5+ and then Qxf7+ — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m13",
    "title": "Queen fork wins the rook: Qh5+",
    "difficulty": "intermediate",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/p6Q/4rk2/8/6p1/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h5",
      "f5e6",
      "h5e5"
    ],
    "hints": {
      "gentle": "Look for a single move that gives check and also attacks a bigger piece.",
      "directional": "Play Qh5+ (check). After the king moves, Qxe5+ wins the rook.",
      "reveal": "Play Qh5+ and then Qxe5+ — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "m14",
    "title": "Skewer wins the rook: Bc2+",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/6r1/5k2/6p1/2p4p/8/K2B4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "d1c2",
      "f5e6",
      "c2g6"
    ],
    "hints": {
      "gentle": "Line up a check so the king must step aside, exposing the piece behind it.",
      "directional": "Play Bc2+ (check). After the king moves, Bxg6 wins the rook.",
      "reveal": "Play Bc2+ and then Bxg6 — winning the rook."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m15",
    "title": "Skewer wins the rook: Bc2+",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/7r/2p5/1p3k2/8/8/8/K2B4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "d1c2",
      "f5e6",
      "c2h7"
    ],
    "hints": {
      "gentle": "Line up a check so the king must step aside, exposing the piece behind it.",
      "directional": "Play Bc2+ (check). After the king moves, Bxh7 wins the rook.",
      "reveal": "Play Bc2+ and then Bxh7 — winning the rook."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m16",
    "title": "Skewer wins the rook: Bd3+",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/B7/5k2/8/5p2/2r1p1p1/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a6d3",
      "f5e6",
      "d3c2"
    ],
    "hints": {
      "gentle": "Line up a check so the king must step aside, exposing the piece behind it.",
      "directional": "Play Bd3+ (check). After the king moves, Bxc2 wins the rook.",
      "reveal": "Play Bd3+ and then Bxc2 — winning the rook."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m17",
    "title": "Skewer wins the rook: Bc8+",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/B7/5k1p/3p2r1/8/2p5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a6c8",
      "f5f6",
      "c8g4"
    ],
    "hints": {
      "gentle": "A skewer hits the king first; when it moves, the piece behind it falls.",
      "directional": "Play Bc8+ (check). After the king moves, Bxg4 wins the rook.",
      "reveal": "Play Bc8+ and then Bxg4 — winning the rook."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m18",
    "title": "Skewer wins the rook: Bc8+",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/B7/5k2/8/7r/2p5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a6c8",
      "f5f6",
      "c8h3"
    ],
    "hints": {
      "gentle": "Line up a check so the king must step aside, exposing the piece behind it.",
      "directional": "Play Bc8+ (check). After the king moves, Bxh3 wins the rook.",
      "reveal": "Play Bc8+ and then Bxh3 — winning the rook."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m19",
    "title": "Skewer wins the rook: Bd3+",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/1p1p3p/B5r1/5k2/8/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a6d3",
      "f5e6",
      "d3g6"
    ],
    "hints": {
      "gentle": "A skewer hits the king first; when it moves, the piece behind it falls.",
      "directional": "Play Bd3+ (check). After the king moves, Bxg6 wins the rook.",
      "reveal": "Play Bd3+ and then Bxg6 — winning the rook."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m20",
    "title": "Skewer wins the rook: Rf2+",
    "difficulty": "intermediate",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/5r2/8/5k2/8/1p6/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2f2",
      "f5e6",
      "f2f7"
    ],
    "hints": {
      "gentle": "A skewer hits the king first; when it moves, the piece behind it falls.",
      "directional": "Play Rf2+ (check). After the king moves, Rxf7 wins the rook.",
      "reveal": "Play Rf2+ and then Rxf7 — winning the rook."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "m21",
    "title": "Mate in one: Qa4#",
    "difficulty": "intermediate",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "4Q3/p7/8/7p/8/2p5/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e8a4"
    ],
    "hints": {
      "gentle": "Mate is available right now. Which check leaves the king no square, no block, no capture?",
      "directional": "Bring the queen to a4; it covers every escape square.",
      "reveal": "Play Qa4# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "m22",
    "title": "Mate in one: Qa6#",
    "difficulty": "intermediate",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/8/8/1Q3p2/4p3/4p3/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "b5a6"
    ],
    "hints": {
      "gentle": "One move ends it. Find the check that the king cannot escape.",
      "directional": "Bring the queen to a6; it covers every escape square.",
      "reveal": "Play Qa6# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "m23",
    "title": "Mate in one: Qa3#",
    "difficulty": "intermediate",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/2p5/3Q4/8/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "d6a3"
    ],
    "hints": {
      "gentle": "One move ends it. Find the check that the king cannot escape.",
      "directional": "Bring the queen to a3; it covers every escape square.",
      "reveal": "Play Qa3# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "m24",
    "title": "Mate in one: Qa7#",
    "difficulty": "intermediate",
    "themes": [
      "mateIn1"
    ],
    "phase": "endgame",
    "fen": "8/5Q2/8/8/8/4p3/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f7a7"
    ],
    "hints": {
      "gentle": "One move ends it. Find the check that the king cannot escape.",
      "directional": "Bring the queen to a7; it covers every escape square.",
      "reveal": "Play Qa7# — checkmate."
    },
    "teachingPoint": "Look for forcing checks where the king has no escape, no block, and no capture.",
    "source": "generated"
  },
  {
    "id": "m25",
    "title": "Win the loose queen on e2 (Rxe2)",
    "difficulty": "intermediate",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/p7/3P4/5k2/8/1p6/2R1q3/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2e2"
    ],
    "hints": {
      "gentle": "Something is hanging. Look for the capture that costs you nothing.",
      "directional": "Your rook can take the queen on e2 — it has no defender.",
      "reveal": "Play Rxe2, winning the queen for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "m26",
    "title": "Win the loose queen on c6 (Rxc6)",
    "difficulty": "intermediate",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/2q5/5k2/8/8/2R2p2/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c6"
    ],
    "hints": {
      "gentle": "Something is hanging. Look for the capture that costs you nothing.",
      "directional": "Your rook can take the queen on c6 — it has no defender.",
      "reveal": "Play Rxc6, winning the queen for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "m27",
    "title": "Win the loose queen on h2 (Rxh2)",
    "difficulty": "intermediate",
    "themes": [
      "hangingPiece"
    ],
    "phase": "middlegame",
    "fen": "8/8/4p3/5k2/2p1p3/8/2R4q/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2h2"
    ],
    "hints": {
      "gentle": "Something is hanging. Look for the capture that costs you nothing.",
      "directional": "Your rook can take the queen on h2 — it has no defender.",
      "reveal": "Play Rxh2, winning the queen for free."
    },
    "teachingPoint": "Before every move, scan for undefended enemy pieces. Winning free material is the simplest edge.",
    "source": "generated"
  },
  {
    "id": "a01",
    "title": "Mate in two: Rh1+",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/4p3/5ppR/5R2/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two. Start with the check that allows only one reply.",
      "directional": "Begin with Rh1+; after the only legal reply, Ra5# is mate.",
      "reveal": "Play Rh1+ Ka2 Ra5# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "a02",
    "title": "Mate in two: Re1+",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/8/8/5R2/2p1p3/2p1R1P1/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e3e1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "Two moves to mate. The first must be a check with exactly one legal response.",
      "directional": "Begin with Re1+; after the only legal reply, Ra5# is mate.",
      "reveal": "Play Re1+ Ka2 Ra5# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "a03",
    "title": "Mate in two: Rb1+",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "1R6/8/5P2/5R2/8/6p1/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "b8b1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "Two moves to mate. The first must be a check with exactly one legal response.",
      "directional": "Begin with Rb1+; after the only legal reply, Ra5# is mate.",
      "reveal": "Play Rb1+ Ka2 Ra5# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "a04",
    "title": "Mate in two: Rf1+",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/7p/3p4/5R2/6R1/7p/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f5f1",
      "a1a2",
      "g4a4"
    ],
    "hints": {
      "gentle": "Two moves to mate. The first must be a check with exactly one legal response.",
      "directional": "Begin with Rf1+; after the only legal reply, Ra4# is mate.",
      "reveal": "Play Rf1+ Ka2 Ra4# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "a05",
    "title": "Mate in two: Rf1+",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/6p1/8/5R2/8/8/2K2R2/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f2f1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "A forcing check limits the king to a single answer — then mate follows.",
      "directional": "Begin with Rf1+; after the only legal reply, Ra5# is mate.",
      "reveal": "Play Rf1+ Ka2 Ra5# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "a06",
    "title": "Mate in two: Rf1+",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/2R5/6p1/5R2/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f5f1",
      "a1a2",
      "c7a7"
    ],
    "hints": {
      "gentle": "A forcing check limits the king to a single answer — then mate follows.",
      "directional": "Begin with Rf1+; after the only legal reply, Ra7# is mate.",
      "reveal": "Play Rf1+ Ka2 Ra7# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "a07",
    "title": "Mate in two: Rh1+",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/8/7p/5R2/8/7R/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h3h1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "Two moves to mate. The first must be a check with exactly one legal response.",
      "directional": "Begin with Rh1+; after the only legal reply, Ra5# is mate.",
      "reveal": "Play Rh1+ Ka2 Ra5# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "a08",
    "title": "Mate in two: Re1+",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "4R3/5p2/8/5R2/8/8/2Kp1p2/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e8e1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "Two moves to mate. The first must be a check with exactly one legal response.",
      "directional": "Begin with Re1+; after the only legal reply, Ra5# is mate.",
      "reveal": "Play Re1+ Ka2 Ra5# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "a09",
    "title": "Mate in two: Rb1+",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/8/8/1R3R2/5p2/7p/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "b5b1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "You can force checkmate in two. Start with the check that allows only one reply.",
      "directional": "Begin with Rb1+; after the only legal reply, Ra5# is mate.",
      "reveal": "Play Rb1+ Ka2 Ra5# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "a10",
    "title": "Mate in two: Rd1+",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/8/3R4/5Rp1/8/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "d6d1",
      "a1a2",
      "f5a5"
    ],
    "hints": {
      "gentle": "A forcing check limits the king to a single answer — then mate follows.",
      "directional": "Begin with Rd1+; after the only legal reply, Ra5# is mate.",
      "reveal": "Play Rd1+ Ka2 Ra5# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "a11",
    "title": "Mate in two: Rf1+",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/5R2/8/4pR2/8/8/1PK5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f5f1",
      "a1a2",
      "f7a7"
    ],
    "hints": {
      "gentle": "Two moves to mate. The first must be a check with exactly one legal response.",
      "directional": "Begin with Rf1+; after the only legal reply, Ra7# is mate.",
      "reveal": "Play Rf1+ Ka2 Ra7# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "a12",
    "title": "Mate in two: Rf1+",
    "difficulty": "advanced",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/8/1p6/5R2/2R1p3/8/2K5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "f5f1",
      "a1a2",
      "c4a4"
    ],
    "hints": {
      "gentle": "Two moves to mate. The first must be a check with exactly one legal response.",
      "directional": "Begin with Rf1+; after the only legal reply, Ra4# is mate.",
      "reveal": "Play Rf1+ Ka2 Ra4# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "a13",
    "title": "Skewer wins the queen: Rf2+",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/5q2/8/5k2/8/p3P3/p1R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2f2",
      "f5e6",
      "f2f7"
    ],
    "hints": {
      "gentle": "Line up a check so the king must step aside, exposing the piece behind it.",
      "directional": "Play Rf2+ (check). After the king moves, Rxf7 wins the queen.",
      "reveal": "Play Rf2+ and then Rxf7 — winning the queen."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a14",
    "title": "Skewer wins the queen: Rxc5+",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/8/2p2k1q/8/8/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c5",
      "f5e6",
      "c5h5"
    ],
    "hints": {
      "gentle": "A skewer hits the king first; when it moves, the piece behind it falls.",
      "directional": "Play Rxc5+ (check). After the king moves, Rxh5 wins the queen.",
      "reveal": "Play Rxc5+ and then Rxh5 — winning the queen."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a15",
    "title": "Skewer wins the queen: Rc5+",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/p7/5kq1/8/1p1p4/1PR5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c5",
      "f5e6",
      "c5g5"
    ],
    "hints": {
      "gentle": "A skewer hits the king first; when it moves, the piece behind it falls.",
      "directional": "Play Rc5+ (check). After the king moves, Rxg5 wins the queen.",
      "reveal": "Play Rc5+ and then Rxg5 — winning the queen."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a16",
    "title": "Skewer wins the queen: Rf2+",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "5q2/1p6/8/5k2/3p4/8/2R5/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2f2",
      "f5e6",
      "f2f8"
    ],
    "hints": {
      "gentle": "Line up a check so the king must step aside, exposing the piece behind it.",
      "directional": "Play Rf2+ (check). After the king moves, Rxf8 wins the queen.",
      "reveal": "Play Rf2+ and then Rxf8 — winning the queen."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a17",
    "title": "Skewer wins the queen: Rh5+",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/5p1R/1q3k2/8/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h5",
      "f5e6",
      "h5b5"
    ],
    "hints": {
      "gentle": "Line up a check so the king must step aside, exposing the piece behind it.",
      "directional": "Play Rh5+ (check). After the king moves, Rxb5 wins the queen.",
      "reveal": "Play Rh5+ and then Rxb5 — winning the queen."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a18",
    "title": "Skewer wins the queen: Rh5+",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/5p1R/3q1k2/8/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h5",
      "f5e6",
      "h5d5"
    ],
    "hints": {
      "gentle": "A skewer hits the king first; when it moves, the piece behind it falls.",
      "directional": "Play Rh5+ (check). After the king moves, Rxd5 wins the queen.",
      "reveal": "Play Rh5+ and then Rxd5 — winning the queen."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a19",
    "title": "Skewer wins the queen: Rh5+",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/1p5R/2q2k2/8/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h5",
      "f5e6",
      "h5c5"
    ],
    "hints": {
      "gentle": "Line up a check so the king must step aside, exposing the piece behind it.",
      "directional": "Play Rh5+ (check). After the king moves, Rxc5 wins the queen.",
      "reveal": "Play Rh5+ and then Rxc5 — winning the queen."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a20",
    "title": "Skewer wins the queen: Rf3+",
    "difficulty": "advanced",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/5q2/2P5/5kp1/1p6/4R1p1/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "e3f3",
      "f5e6",
      "f3f7"
    ],
    "hints": {
      "gentle": "A skewer hits the king first; when it moves, the piece behind it falls.",
      "directional": "Play Rf3+ (check). After the king moves, Rxf7 wins the queen.",
      "reveal": "Play Rf3+ and then Rxf7 — winning the queen."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "a21",
    "title": "Queen fork wins the rook: Qh7+",
    "difficulty": "advanced",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/5p2/3p3Q/5k2/5p2/3r4/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6h7",
      "f5e6",
      "h7d3"
    ],
    "hints": {
      "gentle": "Look for a single move that gives check and also attacks a bigger piece.",
      "directional": "Play Qh7+ (check). After the king moves, Qxd3 wins the rook.",
      "reveal": "Play Qh7+ and then Qxd3 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "a22",
    "title": "Queen fork wins the rook: Qf8+",
    "difficulty": "advanced",
    "themes": [
      "fork"
    ],
    "phase": "middlegame",
    "fen": "8/8/7Q/1p3k2/5r2/8/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "h6f8",
      "f5e6",
      "f8f4"
    ],
    "hints": {
      "gentle": "A queen can attack two things at once — find the move that checks and forks.",
      "directional": "Play Qf8+ (check). After the king moves, Qxf4 wins the rook.",
      "reveal": "Play Qf8+ and then Qxf4 — winning the rook."
    },
    "teachingPoint": "A fork with check is decisive: the king must answer the check first, so the second target is lost.",
    "source": "generated"
  },
  {
    "id": "a23",
    "title": "Promote with capture: axb8=Q",
    "difficulty": "advanced",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "1r6/P2p4/8/8/6k1/6p1/6p1/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7b8q"
    ],
    "hints": {
      "gentle": "Your pawn is one step from the far rank. Turn it into your strongest piece.",
      "directional": "Capture into promotion with axb8=Q, making a new queen.",
      "reveal": "Play axb8=Q, gaining a queen."
    },
    "teachingPoint": "A pawn reaching the far rank promotes, almost always to a queen — a decisive endgame weapon.",
    "source": "generated"
  },
  {
    "id": "a24",
    "title": "Promote with capture: axb8=Q",
    "difficulty": "advanced",
    "themes": [
      "promotion"
    ],
    "phase": "endgame",
    "fen": "1r6/P7/8/1p6/4P3/8/8/K2k4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a7b8q"
    ],
    "hints": {
      "gentle": "Your pawn is one step from the far rank. Turn it into your strongest piece.",
      "directional": "Capture into promotion with axb8=Q, making a new queen.",
      "reveal": "Play axb8=Q, gaining a queen."
    },
    "teachingPoint": "A pawn reaching the far rank promotes, almost always to a queen — a decisive endgame weapon.",
    "source": "generated"
  },
  {
    "id": "e01",
    "title": "Mate in two: Qc1+",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/4p3/8/p4K2/5p2/4R3/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c1",
      "a1a2",
      "e3a3"
    ],
    "hints": {
      "gentle": "Two moves to mate. The first must be a check with exactly one legal response.",
      "directional": "Begin with Qc1+; after the only legal reply, Ra3# is mate.",
      "reveal": "Play Qc1+ Ka2 Ra3# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "e02",
    "title": "Mate in two: Qxc3+",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "1R6/8/3P4/5K2/8/2p4p/2Q4p/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c3",
      "a1a2",
      "c3a5"
    ],
    "hints": {
      "gentle": "Two moves to mate. The first must be a check with exactly one legal response.",
      "directional": "Begin with Qxc3+; after the only legal reply, Qa5# is mate.",
      "reveal": "Play Qxc3+ Ka2 Qa5# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "e03",
    "title": "Mate in two: Qa4+",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/8/1p6/5K2/8/8/2Q2R2/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2a4",
      "a1b1",
      "a4d1"
    ],
    "hints": {
      "gentle": "You can force checkmate in two. Start with the check that allows only one reply.",
      "directional": "Begin with Qa4+; after the only legal reply, Qd1# is mate.",
      "reveal": "Play Qa4+ Kb1 Qd1# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "e04",
    "title": "Mate in two: Qc1+",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/8/8/2p2K2/8/7R/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c1",
      "a1a2",
      "h3a3"
    ],
    "hints": {
      "gentle": "Two moves to mate. The first must be a check with exactly one legal response.",
      "directional": "Begin with Qc1+; after the only legal reply, Ra3# is mate.",
      "reveal": "Play Qc1+ Ka2 Ra3# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "e05",
    "title": "Mate in two: Qc3+",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/3p1p2/8/1R3K1p/8/8/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c3",
      "a1a2",
      "c3a5"
    ],
    "hints": {
      "gentle": "A forcing check limits the king to a single answer — then mate follows.",
      "directional": "Begin with Qc3+; after the only legal reply, Qa5# is mate.",
      "reveal": "Play Qc3+ Ka2 Qa5# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "e06",
    "title": "Mate in two: Qc1+",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/8/8/5K2/8/3R4/2Q4p/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c1",
      "a1a2",
      "d3a3"
    ],
    "hints": {
      "gentle": "You can force checkmate in two. Start with the check that allows only one reply.",
      "directional": "Begin with Qc1+; after the only legal reply, Ra3# is mate.",
      "reveal": "Play Qc1+ Ka2 Ra3# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "e07",
    "title": "Mate in two: Qa4+",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/6p1/p7/5K2/8/5P2/2Q1Rp2/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2a4",
      "a1b1",
      "a4d1"
    ],
    "hints": {
      "gentle": "Two moves to mate. The first must be a check with exactly one legal response.",
      "directional": "Begin with Qa4+; after the only legal reply, Qd1# is mate.",
      "reveal": "Play Qa4+ Kb1 Qd1# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "e08",
    "title": "Mate in two: Qc3+",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/1R6/8/5K2/8/3p4/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c3",
      "a1a2",
      "c3a5"
    ],
    "hints": {
      "gentle": "A forcing check limits the king to a single answer — then mate follows.",
      "directional": "Begin with Qc3+; after the only legal reply, Qa5# is mate.",
      "reveal": "Play Qc3+ Ka2 Qa5# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "e09",
    "title": "Mate in two: Qc1+",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/8/5p2/5K2/8/6R1/2Q5/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2c1",
      "a1a2",
      "g3a3"
    ],
    "hints": {
      "gentle": "A forcing check limits the king to a single answer — then mate follows.",
      "directional": "Begin with Qc1+; after the only legal reply, Ra3# is mate.",
      "reveal": "Play Qc1+ Ka2 Ra3# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "e10",
    "title": "Mate in two: Qa4+",
    "difficulty": "expert",
    "themes": [
      "mateIn2"
    ],
    "phase": "endgame",
    "fen": "8/8/8/5K2/8/2p5/2Q4R/k7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "c2a4",
      "a1b1",
      "a4d1"
    ],
    "hints": {
      "gentle": "A forcing check limits the king to a single answer — then mate follows.",
      "directional": "Begin with Qa4+; after the only legal reply, Qd1# is mate.",
      "reveal": "Play Qa4+ Kb1 Qd1# — the line ends in checkmate."
    },
    "teachingPoint": "Forcing checks that leave a single legal reply let you calculate the mate all the way to the end.",
    "source": "generated"
  },
  {
    "id": "e11",
    "title": "Skewer wins the queen: Bxc2+",
    "difficulty": "expert",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/1P6/6q1/5k2/7p/8/2p5/K2B4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "d1c2",
      "f5e6",
      "c2g6"
    ],
    "hints": {
      "gentle": "Line up a check so the king must step aside, exposing the piece behind it.",
      "directional": "Play Bxc2+ (check). After the king moves, Bxg6 wins the queen.",
      "reveal": "Play Bxc2+ and then Bxg6 — winning the queen."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "e12",
    "title": "Skewer wins the queen: Bc2+",
    "difficulty": "expert",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/p6q/8/5kp1/5p2/8/8/K2B4 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "d1c2",
      "f5e6",
      "c2h7"
    ],
    "hints": {
      "gentle": "A skewer hits the king first; when it moves, the piece behind it falls.",
      "directional": "Play Bc2+ (check). After the king moves, Bxh7 wins the queen.",
      "reveal": "Play Bc2+ and then Bxh7 — winning the queen."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "e13",
    "title": "Skewer wins the queen: Bc8+",
    "difficulty": "expert",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/B7/2p2k2/6q1/3P4/4p3/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a6c8",
      "f5f6",
      "c8g4"
    ],
    "hints": {
      "gentle": "Line up a check so the king must step aside, exposing the piece behind it.",
      "directional": "Play Bc8+ (check). After the king moves, Bxg4 wins the queen.",
      "reveal": "Play Bc8+ and then Bxg4 — winning the queen."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  },
  {
    "id": "e14",
    "title": "Skewer wins the queen: Bc8+",
    "difficulty": "expert",
    "themes": [
      "skewer"
    ],
    "phase": "middlegame",
    "fen": "8/8/B6p/5k2/7P/7q/8/K7 w - - 0 1",
    "sideToMove": "w",
    "solution": [
      "a6c8",
      "f5f6",
      "c8h3"
    ],
    "hints": {
      "gentle": "Line up a check so the king must step aside, exposing the piece behind it.",
      "directional": "Play Bc8+ (check). After the king moves, Bxh3 wins the queen.",
      "reveal": "Play Bc8+ and then Bxh3 — winning the queen."
    },
    "teachingPoint": "A skewer checks a piece in front; when it moves, you capture the piece lined up behind it.",
    "source": "generated"
  }
];
